// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PayloadLog {
    pub uid: u64,
    pub entity_reference: u32,
    pub tic: u16,
    pub payload: Vec::<u32>,
}


impl __sdk::InModule for PayloadLog {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `PayloadLog`.
///
/// Provides typed access to columns for query building.
pub struct PayloadLogCols {
    pub uid: __sdk::__query_builder::Col<PayloadLog, u64>,
    pub entity_reference: __sdk::__query_builder::Col<PayloadLog, u32>,
    pub tic: __sdk::__query_builder::Col<PayloadLog, u16>,
    pub payload: __sdk::__query_builder::Col<PayloadLog, Vec::<u32>>,
}

impl __sdk::__query_builder::HasCols for PayloadLog {
    type Cols = PayloadLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PayloadLogCols {
            uid: __sdk::__query_builder::Col::new(table_name, "uid"),
            entity_reference: __sdk::__query_builder::Col::new(table_name, "entity_reference"),
            tic: __sdk::__query_builder::Col::new(table_name, "tic"),
            payload: __sdk::__query_builder::Col::new(table_name, "payload"),

        }
    }
}

/// Indexed column accessor struct for the table `PayloadLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct PayloadLogIxCols {
    pub entity_reference: __sdk::__query_builder::IxCol<PayloadLog, u32>,
    pub uid: __sdk::__query_builder::IxCol<PayloadLog, u64>,
}

impl __sdk::__query_builder::HasIxCols for PayloadLog {
    type IxCols = PayloadLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PayloadLogIxCols {
            entity_reference: __sdk::__query_builder::IxCol::new(table_name, "entity_reference"),
            uid: __sdk::__query_builder::IxCol::new(table_name, "uid"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PayloadLog {}

