// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendChatMessageArgs {
    pub sender_player_id: u32,
    pub sender_name: String,
    pub body: String,
}

impl From<SendChatMessageArgs> for super::Reducer {
    fn from(args: SendChatMessageArgs) -> Self {
        Self::SendChatMessage {
            sender_player_id: args.sender_player_id,
            sender_name: args.sender_name,
            body: args.body,
}
}
}

impl __sdk::InModule for SendChatMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_chat_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_chat_message {
    /// Request that the remote module invoke the reducer `send_chat_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`send_chat_message:send_chat_message_then`] to run a callback after the reducer completes.
    fn send_chat_message(&self, sender_player_id: u32,
sender_name: String,
body: String,
) -> __sdk::Result<()> {
        self.send_chat_message_then(sender_player_id, sender_name, body,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `send_chat_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn send_chat_message_then(
        &self,
        sender_player_id: u32,
sender_name: String,
body: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl send_chat_message for super::RemoteReducers {
    fn send_chat_message_then(
        &self,
        sender_player_id: u32,
sender_name: String,
body: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SendChatMessageArgs { sender_player_id, sender_name, body,  }, callback)
    }
}

