// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AssignPlayerArgs {
    pub player_id: u32,
    pub server_id: u16,
    pub now_ms: u64,
}

impl From<AssignPlayerArgs> for super::Reducer {
    fn from(args: AssignPlayerArgs) -> Self {
        Self::AssignPlayer {
            player_id: args.player_id,
            server_id: args.server_id,
            now_ms: args.now_ms,
}
}
}

impl __sdk::InModule for AssignPlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `assign_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait assign_player {
    /// Request that the remote module invoke the reducer `assign_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`assign_player:assign_player_then`] to run a callback after the reducer completes.
    fn assign_player(&self, player_id: u32,
server_id: u16,
now_ms: u64,
) -> __sdk::Result<()> {
        self.assign_player_then(player_id, server_id, now_ms,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `assign_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn assign_player_then(
        &self,
        player_id: u32,
server_id: u16,
now_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl assign_player for super::RemoteReducers {
    fn assign_player_then(
        &self,
        player_id: u32,
server_id: u16,
now_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AssignPlayerArgs { player_id, server_id, now_ms,  }, callback)
    }
}

