// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BumpTicArgs {
    pub realm: u8,
}

impl From<BumpTicArgs> for super::Reducer {
    fn from(args: BumpTicArgs) -> Self {
        Self::BumpTic {
            realm: args.realm,
}
}
}

impl __sdk::InModule for BumpTicArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bump_tic`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bump_tic {
    /// Request that the remote module invoke the reducer `bump_tic` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bump_tic:bump_tic_then`] to run a callback after the reducer completes.
    fn bump_tic(&self, realm: u8,
) -> __sdk::Result<()> {
        self.bump_tic_then(realm,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `bump_tic` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bump_tic_then(
        &self,
        realm: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl bump_tic for super::RemoteReducers {
    fn bump_tic_then(
        &self,
        realm: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(BumpTicArgs { realm,  }, callback)
    }
}

