// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnsureDefinitionArgs {
    pub id: u32,
    pub version: u32,
    pub type_name: String,
    pub sub_type: String,
    pub kind: String,
    pub variant: String,
}

impl From<EnsureDefinitionArgs> for super::Reducer {
    fn from(args: EnsureDefinitionArgs) -> Self {
        Self::EnsureDefinition {
            id: args.id,
            version: args.version,
            type_name: args.type_name,
            sub_type: args.sub_type,
            kind: args.kind,
            variant: args.variant,
}
}
}

impl __sdk::InModule for EnsureDefinitionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ensure_definition`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ensure_definition {
    /// Request that the remote module invoke the reducer `ensure_definition` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ensure_definition:ensure_definition_then`] to run a callback after the reducer completes.
    fn ensure_definition(&self, id: u32,
version: u32,
type_name: String,
sub_type: String,
kind: String,
variant: String,
) -> __sdk::Result<()> {
        self.ensure_definition_then(id, version, type_name, sub_type, kind, variant,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ensure_definition` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ensure_definition_then(
        &self,
        id: u32,
version: u32,
type_name: String,
sub_type: String,
kind: String,
variant: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ensure_definition for super::RemoteReducers {
    fn ensure_definition_then(
        &self,
        id: u32,
version: u32,
type_name: String,
sub_type: String,
kind: String,
variant: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(EnsureDefinitionArgs { id, version, type_name, sub_type, kind, variant,  }, callback)
    }
}

