// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::master_clock_type::MasterClock;

/// Table handle for the table `master_clock`.
///
/// Obtain a handle from the [`MasterClockTableAccess::master_clock`] method on [`super::RemoteTables`],
/// like `ctx.db.master_clock()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.master_clock().on_insert(...)`.
pub struct MasterClockTableHandle<'ctx> {
    imp: __sdk::TableHandle<MasterClock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `master_clock`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MasterClockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MasterClockTableHandle`], which mediates access to the table `master_clock`.
    fn master_clock(&self) -> MasterClockTableHandle<'_>;
}

impl MasterClockTableAccess for super::RemoteTables {
    fn master_clock(&self) -> MasterClockTableHandle<'_> {
        MasterClockTableHandle {
            imp: self.imp.get_table::<MasterClock>("master_clock"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MasterClockInsertCallbackId(__sdk::CallbackId);
pub struct MasterClockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MasterClockTableHandle<'ctx> {
    type Row = MasterClock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = MasterClock> + '_ { self.imp.iter() }

    type InsertCallbackId = MasterClockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MasterClockInsertCallbackId {
        MasterClockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MasterClockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MasterClockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MasterClockDeleteCallbackId {
        MasterClockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MasterClockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MasterClockUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MasterClockTableHandle<'ctx> {
    type UpdateCallbackId = MasterClockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MasterClockUpdateCallbackId {
        MasterClockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MasterClockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `realm` unique index on the table `master_clock`,
        /// which allows point queries on the field of the same name
        /// via the [`MasterClockRealmUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.master_clock().realm().find(...)`.
        pub struct MasterClockRealmUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<MasterClock, u8>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> MasterClockTableHandle<'ctx> {
            /// Get a handle on the `realm` unique index on the table `master_clock`.
            pub fn realm(&self) -> MasterClockRealmUnique<'ctx> {
                MasterClockRealmUnique {
                    imp: self.imp.get_unique_constraint::<u8>("realm"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> MasterClockRealmUnique<'ctx> {
            /// Find the subscribed row whose `realm` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u8) -> Option<MasterClock> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<MasterClock>("master_clock");
    _table.add_unique_constraint::<u8>("realm", |row| &row.realm);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MasterClock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<MasterClock>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `MasterClock`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait master_clockQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `MasterClock`.
            fn master_clock(&self) -> __sdk::__query_builder::Table<MasterClock>;
        }

        impl master_clockQueryTableAccess for __sdk::QueryTableAccessor {
            fn master_clock(&self) -> __sdk::__query_builder::Table<MasterClock> {
                __sdk::__query_builder::Table::new("master_clock")
            }
        }

