// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendEventArgs {
    pub from_server_id: u16,
    pub actor_shard_id: u16,
    pub actor_key: u64,
    pub target_key: u64,
    pub action: u16,
    pub data_0: u64,
    pub data_1: u64,
}

impl From<AppendEventArgs> for super::Reducer {
    fn from(args: AppendEventArgs) -> Self {
        Self::AppendEvent {
            from_server_id: args.from_server_id,
            actor_shard_id: args.actor_shard_id,
            actor_key: args.actor_key,
            target_key: args.target_key,
            action: args.action,
            data_0: args.data_0,
            data_1: args.data_1,
}
}
}

impl __sdk::InModule for AppendEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_event {
    /// Request that the remote module invoke the reducer `append_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_event:append_event_then`] to run a callback after the reducer completes.
    fn append_event(&self, from_server_id: u16,
actor_shard_id: u16,
actor_key: u64,
target_key: u64,
action: u16,
data_0: u64,
data_1: u64,
) -> __sdk::Result<()> {
        self.append_event_then(from_server_id, actor_shard_id, actor_key, target_key, action, data_0, data_1,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_event_then(
        &self,
        from_server_id: u16,
actor_shard_id: u16,
actor_key: u64,
target_key: u64,
action: u16,
data_0: u64,
data_1: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_event for super::RemoteReducers {
    fn append_event_then(
        &self,
        from_server_id: u16,
actor_shard_id: u16,
actor_key: u64,
target_key: u64,
action: u16,
data_0: u64,
data_1: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AppendEventArgs { from_server_id, actor_shard_id, actor_key, target_key, action, data_0, data_1,  }, callback)
    }
}

