// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EventLog {
    pub event_reference: u64,
    pub event_tic: u32,
    pub from_server_id: u16,
    pub actor_shard_id: u16,
    pub actor_key: u64,
    pub target_key: u64,
    pub action: u16,
    pub data_0: u64,
    pub data_1: u64,
    pub status: u8,
}


impl __sdk::InModule for EventLog {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `EventLog`.
///
/// Provides typed access to columns for query building.
pub struct EventLogCols {
    pub event_reference: __sdk::__query_builder::Col<EventLog, u64>,
    pub event_tic: __sdk::__query_builder::Col<EventLog, u32>,
    pub from_server_id: __sdk::__query_builder::Col<EventLog, u16>,
    pub actor_shard_id: __sdk::__query_builder::Col<EventLog, u16>,
    pub actor_key: __sdk::__query_builder::Col<EventLog, u64>,
    pub target_key: __sdk::__query_builder::Col<EventLog, u64>,
    pub action: __sdk::__query_builder::Col<EventLog, u16>,
    pub data_0: __sdk::__query_builder::Col<EventLog, u64>,
    pub data_1: __sdk::__query_builder::Col<EventLog, u64>,
    pub status: __sdk::__query_builder::Col<EventLog, u8>,
}

impl __sdk::__query_builder::HasCols for EventLog {
    type Cols = EventLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventLogCols {
            event_reference: __sdk::__query_builder::Col::new(table_name, "event_reference"),
            event_tic: __sdk::__query_builder::Col::new(table_name, "event_tic"),
            from_server_id: __sdk::__query_builder::Col::new(table_name, "from_server_id"),
            actor_shard_id: __sdk::__query_builder::Col::new(table_name, "actor_shard_id"),
            actor_key: __sdk::__query_builder::Col::new(table_name, "actor_key"),
            target_key: __sdk::__query_builder::Col::new(table_name, "target_key"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            data_0: __sdk::__query_builder::Col::new(table_name, "data_0"),
            data_1: __sdk::__query_builder::Col::new(table_name, "data_1"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),

        }
    }
}

/// Indexed column accessor struct for the table `EventLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventLogIxCols {
    pub event_reference: __sdk::__query_builder::IxCol<EventLog, u64>,
    pub event_tic: __sdk::__query_builder::IxCol<EventLog, u32>,
    pub target_key: __sdk::__query_builder::IxCol<EventLog, u64>,
}

impl __sdk::__query_builder::HasIxCols for EventLog {
    type IxCols = EventLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventLogIxCols {
            event_reference: __sdk::__query_builder::IxCol::new(table_name, "event_reference"),
            event_tic: __sdk::__query_builder::IxCol::new(table_name, "event_tic"),
            target_key: __sdk::__query_builder::IxCol::new(table_name, "target_key"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EventLog {}

