// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::shard_meta_type::ShardMeta;

/// Table handle for the table `shard_meta`.
///
/// Obtain a handle from the [`ShardMetaTableAccess::shard_meta`] method on [`super::RemoteTables`],
/// like `ctx.db.shard_meta()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.shard_meta().on_insert(...)`.
pub struct ShardMetaTableHandle<'ctx> {
    imp: __sdk::TableHandle<ShardMeta>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `shard_meta`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ShardMetaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ShardMetaTableHandle`], which mediates access to the table `shard_meta`.
    fn shard_meta(&self) -> ShardMetaTableHandle<'_>;
}

impl ShardMetaTableAccess for super::RemoteTables {
    fn shard_meta(&self) -> ShardMetaTableHandle<'_> {
        ShardMetaTableHandle {
            imp: self.imp.get_table::<ShardMeta>("shard_meta"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ShardMetaInsertCallbackId(__sdk::CallbackId);
pub struct ShardMetaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ShardMetaTableHandle<'ctx> {
    type Row = ShardMeta;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ShardMeta> + '_ { self.imp.iter() }

    type InsertCallbackId = ShardMetaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShardMetaInsertCallbackId {
        ShardMetaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ShardMetaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ShardMetaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ShardMetaDeleteCallbackId {
        ShardMetaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ShardMetaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ShardMetaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ShardMetaTableHandle<'ctx> {
    type UpdateCallbackId = ShardMetaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ShardMetaUpdateCallbackId {
        ShardMetaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ShardMetaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `shard_meta`,
        /// which allows point queries on the field of the same name
        /// via the [`ShardMetaIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.shard_meta().id().find(...)`.
        pub struct ShardMetaIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ShardMeta, u8>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ShardMetaTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `shard_meta`.
            pub fn id(&self) -> ShardMetaIdUnique<'ctx> {
                ShardMetaIdUnique {
                    imp: self.imp.get_unique_constraint::<u8>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ShardMetaIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u8) -> Option<ShardMeta> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ShardMeta>("shard_meta");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ShardMeta>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ShardMeta>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ShardMeta`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait shard_metaQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ShardMeta`.
            fn shard_meta(&self) -> __sdk::__query_builder::Table<ShardMeta>;
        }

        impl shard_metaQueryTableAccess for __sdk::QueryTableAccessor {
            fn shard_meta(&self) -> __sdk::__query_builder::Table<ShardMeta> {
                __sdk::__query_builder::Table::new("shard_meta")
            }
        }

