// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EventLog {
    pub event_reference: u32,
    pub event_tic: u16,
    pub status: u8,
    pub actions: Vec::<u32>,
    pub event_group: u32,
    pub orchestrator_reference: u8,
    pub worker_reference: u8,
    pub zones: Vec::<u16>,
    pub issuer_player_id: u32,
}


impl __sdk::InModule for EventLog {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `EventLog`.
///
/// Provides typed access to columns for query building.
pub struct EventLogCols {
    pub event_reference: __sdk::__query_builder::Col<EventLog, u32>,
    pub event_tic: __sdk::__query_builder::Col<EventLog, u16>,
    pub status: __sdk::__query_builder::Col<EventLog, u8>,
    pub actions: __sdk::__query_builder::Col<EventLog, Vec::<u32>>,
    pub event_group: __sdk::__query_builder::Col<EventLog, u32>,
    pub orchestrator_reference: __sdk::__query_builder::Col<EventLog, u8>,
    pub worker_reference: __sdk::__query_builder::Col<EventLog, u8>,
    pub zones: __sdk::__query_builder::Col<EventLog, Vec::<u16>>,
    pub issuer_player_id: __sdk::__query_builder::Col<EventLog, u32>,
}

impl __sdk::__query_builder::HasCols for EventLog {
    type Cols = EventLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventLogCols {
            event_reference: __sdk::__query_builder::Col::new(table_name, "event_reference"),
            event_tic: __sdk::__query_builder::Col::new(table_name, "event_tic"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            actions: __sdk::__query_builder::Col::new(table_name, "actions"),
            event_group: __sdk::__query_builder::Col::new(table_name, "event_group"),
            orchestrator_reference: __sdk::__query_builder::Col::new(table_name, "orchestrator_reference"),
            worker_reference: __sdk::__query_builder::Col::new(table_name, "worker_reference"),
            zones: __sdk::__query_builder::Col::new(table_name, "zones"),
            issuer_player_id: __sdk::__query_builder::Col::new(table_name, "issuer_player_id"),

        }
    }
}

/// Indexed column accessor struct for the table `EventLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventLogIxCols {
    pub event_group: __sdk::__query_builder::IxCol<EventLog, u32>,
    pub event_reference: __sdk::__query_builder::IxCol<EventLog, u32>,
    pub event_tic: __sdk::__query_builder::IxCol<EventLog, u16>,
    pub orchestrator_reference: __sdk::__query_builder::IxCol<EventLog, u8>,
    pub status: __sdk::__query_builder::IxCol<EventLog, u8>,
    pub worker_reference: __sdk::__query_builder::IxCol<EventLog, u8>,
}

impl __sdk::__query_builder::HasIxCols for EventLog {
    type IxCols = EventLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventLogIxCols {
            event_group: __sdk::__query_builder::IxCol::new(table_name, "event_group"),
            event_reference: __sdk::__query_builder::IxCol::new(table_name, "event_reference"),
            event_tic: __sdk::__query_builder::IxCol::new(table_name, "event_tic"),
            orchestrator_reference: __sdk::__query_builder::IxCol::new(table_name, "orchestrator_reference"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            worker_reference: __sdk::__query_builder::IxCol::new(table_name, "worker_reference"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EventLog {}

