// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FailArgs {
    pub event_reference: u32,
}

impl From<FailArgs> for super::Reducer {
    fn from(args: FailArgs) -> Self {
        Self::Fail {
            event_reference: args.event_reference,
}
}
}

impl __sdk::InModule for FailArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `fail`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait fail {
    /// Request that the remote module invoke the reducer `fail` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`fail:fail_then`] to run a callback after the reducer completes.
    fn fail(&self, event_reference: u32,
) -> __sdk::Result<()> {
        self.fail_then(event_reference,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `fail` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn fail_then(
        &self,
        event_reference: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl fail for super::RemoteReducers {
    fn fail_then(
        &self,
        event_reference: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(FailArgs { event_reference,  }, callback)
    }
}

