// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct State {
    pub entity_reference: u32,
    pub macro_position_reference: u16,
    pub tic: u16,
    pub definition_reference: u32,
    pub position_reference: u32,
    pub data: u8,
}


impl __sdk::InModule for State {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `State`.
///
/// Provides typed access to columns for query building.
pub struct StateCols {
    pub entity_reference: __sdk::__query_builder::Col<State, u32>,
    pub macro_position_reference: __sdk::__query_builder::Col<State, u16>,
    pub tic: __sdk::__query_builder::Col<State, u16>,
    pub definition_reference: __sdk::__query_builder::Col<State, u32>,
    pub position_reference: __sdk::__query_builder::Col<State, u32>,
    pub data: __sdk::__query_builder::Col<State, u8>,
}

impl __sdk::__query_builder::HasCols for State {
    type Cols = StateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StateCols {
            entity_reference: __sdk::__query_builder::Col::new(table_name, "entity_reference"),
            macro_position_reference: __sdk::__query_builder::Col::new(table_name, "macro_position_reference"),
            tic: __sdk::__query_builder::Col::new(table_name, "tic"),
            definition_reference: __sdk::__query_builder::Col::new(table_name, "definition_reference"),
            position_reference: __sdk::__query_builder::Col::new(table_name, "position_reference"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),

        }
    }
}

/// Indexed column accessor struct for the table `State`.
///
/// Provides typed access to indexed columns for query building.
pub struct StateIxCols {
    pub entity_reference: __sdk::__query_builder::IxCol<State, u32>,
    pub macro_position_reference: __sdk::__query_builder::IxCol<State, u16>,
}

impl __sdk::__query_builder::HasIxCols for State {
    type IxCols = StateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StateIxCols {
            entity_reference: __sdk::__query_builder::IxCol::new(table_name, "entity_reference"),
            macro_position_reference: __sdk::__query_builder::IxCol::new(table_name, "macro_position_reference"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for State {}

