// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GcSchedule {
    pub id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}


impl __sdk::InModule for GcSchedule {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `GcSchedule`.
///
/// Provides typed access to columns for query building.
pub struct GcScheduleCols {
    pub id: __sdk::__query_builder::Col<GcSchedule, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<GcSchedule, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for GcSchedule {
    type Cols = GcScheduleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GcScheduleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),

        }
    }
}

/// Indexed column accessor struct for the table `GcSchedule`.
///
/// Provides typed access to indexed columns for query building.
pub struct GcScheduleIxCols {
    pub id: __sdk::__query_builder::IxCol<GcSchedule, u64>,
}

impl __sdk::__query_builder::HasIxCols for GcSchedule {
    type IxCols = GcScheduleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GcScheduleIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GcSchedule {}

