// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LinkPlayerPawnArgs {
    pub player_id: u32,
    pub player_pawn_reference: u32,
}

impl From<LinkPlayerPawnArgs> for super::Reducer {
    fn from(args: LinkPlayerPawnArgs) -> Self {
        Self::LinkPlayerPawn {
            player_id: args.player_id,
            player_pawn_reference: args.player_pawn_reference,
}
}
}

impl __sdk::InModule for LinkPlayerPawnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `link_player_pawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait link_player_pawn {
    /// Request that the remote module invoke the reducer `link_player_pawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`link_player_pawn:link_player_pawn_then`] to run a callback after the reducer completes.
    fn link_player_pawn(&self, player_id: u32,
player_pawn_reference: u32,
) -> __sdk::Result<()> {
        self.link_player_pawn_then(player_id, player_pawn_reference,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `link_player_pawn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn link_player_pawn_then(
        &self,
        player_id: u32,
player_pawn_reference: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl link_player_pawn for super::RemoteReducers {
    fn link_player_pawn_then(
        &self,
        player_id: u32,
player_pawn_reference: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(LinkPlayerPawnArgs { player_id, player_pawn_reference,  }, callback)
    }
}

