// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerProfile {
    pub player_id: u32,
    pub data_shard: u16,
}


impl __sdk::InModule for PlayerProfile {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `PlayerProfile`.
///
/// Provides typed access to columns for query building.
pub struct PlayerProfileCols {
    pub player_id: __sdk::__query_builder::Col<PlayerProfile, u32>,
    pub data_shard: __sdk::__query_builder::Col<PlayerProfile, u16>,
}

impl __sdk::__query_builder::HasCols for PlayerProfile {
    type Cols = PlayerProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerProfileCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            data_shard: __sdk::__query_builder::Col::new(table_name, "data_shard"),

        }
    }
}

/// Indexed column accessor struct for the table `PlayerProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerProfileIxCols {
    pub player_id: __sdk::__query_builder::IxCol<PlayerProfile, u32>,
}

impl __sdk::__query_builder::HasIxCols for PlayerProfile {
    type IxCols = PlayerProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerProfileIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerProfile {}

