// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerPawns {
    pub player_pawn_reference: u32,
    pub player_id: u32,
    pub active: bool,
}


impl __sdk::InModule for PlayerPawns {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `PlayerPawns`.
///
/// Provides typed access to columns for query building.
pub struct PlayerPawnsCols {
    pub player_pawn_reference: __sdk::__query_builder::Col<PlayerPawns, u32>,
    pub player_id: __sdk::__query_builder::Col<PlayerPawns, u32>,
    pub active: __sdk::__query_builder::Col<PlayerPawns, bool>,
}

impl __sdk::__query_builder::HasCols for PlayerPawns {
    type Cols = PlayerPawnsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerPawnsCols {
            player_pawn_reference: __sdk::__query_builder::Col::new(table_name, "player_pawn_reference"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),

        }
    }
}

/// Indexed column accessor struct for the table `PlayerPawns`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerPawnsIxCols {
    pub player_id: __sdk::__query_builder::IxCol<PlayerPawns, u32>,
    pub player_pawn_reference: __sdk::__query_builder::IxCol<PlayerPawns, u32>,
}

impl __sdk::__query_builder::HasIxCols for PlayerPawns {
    type IxCols = PlayerPawnsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerPawnsIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
            player_pawn_reference: __sdk::__query_builder::IxCol::new(table_name, "player_pawn_reference"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerPawns {}

