// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetLastLoginArgs {
    pub client_time_ms: u64,
    pub player_id: u32,
}

impl From<SetLastLoginArgs> for super::Reducer {
    fn from(args: SetLastLoginArgs) -> Self {
        Self::SetLastLogin {
            client_time_ms: args.client_time_ms,
            player_id: args.player_id,
}
}
}

impl __sdk::InModule for SetLastLoginArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_last_login`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_last_login {
    /// Request that the remote module invoke the reducer `set_last_login` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_last_login:set_last_login_then`] to run a callback after the reducer completes.
    fn set_last_login(&self, client_time_ms: u64,
player_id: u32,
) -> __sdk::Result<()> {
        self.set_last_login_then(client_time_ms, player_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_last_login` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_last_login_then(
        &self,
        client_time_ms: u64,
player_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_last_login for super::RemoteReducers {
    fn set_last_login_then(
        &self,
        client_time_ms: u64,
player_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetLastLoginArgs { client_time_ms, player_id,  }, callback)
    }
}

