// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::target_state_type::TargetState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct WriteArgs {
    pub worker: u8,
    pub tic: u16,
    pub results: Vec::<TargetState>,
}

impl From<WriteArgs> for super::Reducer {
    fn from(args: WriteArgs) -> Self {
        Self::Write {
            worker: args.worker,
            tic: args.tic,
            results: args.results,
}
}
}

impl __sdk::InModule for WriteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `write`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait write {
    /// Request that the remote module invoke the reducer `write` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`write:write_then`] to run a callback after the reducer completes.
    fn write(&self, worker: u8,
tic: u16,
results: Vec::<TargetState>,
) -> __sdk::Result<()> {
        self.write_then(worker, tic, results,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `write` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn write_then(
        &self,
        worker: u8,
tic: u16,
results: Vec::<TargetState>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl write for super::RemoteReducers {
    fn write_then(
        &self,
        worker: u8,
tic: u16,
results: Vec::<TargetState>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(WriteArgs { worker, tic, results,  }, callback)
    }
}

