// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::cold_shard_type::ColdShard;

/// Table handle for the table `cold_shards`.
///
/// Obtain a handle from the [`ColdShardsTableAccess::cold_shards`] method on [`super::RemoteTables`],
/// like `ctx.db.cold_shards()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cold_shards().on_insert(...)`.
pub struct ColdShardsTableHandle<'ctx> {
    imp: __sdk::TableHandle<ColdShard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cold_shards`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ColdShardsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ColdShardsTableHandle`], which mediates access to the table `cold_shards`.
    fn cold_shards(&self) -> ColdShardsTableHandle<'_>;
}

impl ColdShardsTableAccess for super::RemoteTables {
    fn cold_shards(&self) -> ColdShardsTableHandle<'_> {
        ColdShardsTableHandle {
            imp: self.imp.get_table::<ColdShard>("cold_shards"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ColdShardsInsertCallbackId(__sdk::CallbackId);
pub struct ColdShardsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ColdShardsTableHandle<'ctx> {
    type Row = ColdShard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ColdShard> + '_ { self.imp.iter() }

    type InsertCallbackId = ColdShardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColdShardsInsertCallbackId {
        ColdShardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ColdShardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ColdShardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColdShardsDeleteCallbackId {
        ColdShardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ColdShardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ColdShardsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ColdShardsTableHandle<'ctx> {
    type UpdateCallbackId = ColdShardsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ColdShardsUpdateCallbackId {
        ColdShardsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ColdShardsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `route_reference` unique index on the table `cold_shards`,
        /// which allows point queries on the field of the same name
        /// via the [`ColdShardsRouteReferenceUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.cold_shards().route_reference().find(...)`.
        pub struct ColdShardsRouteReferenceUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ColdShard, u16>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ColdShardsTableHandle<'ctx> {
            /// Get a handle on the `route_reference` unique index on the table `cold_shards`.
            pub fn route_reference(&self) -> ColdShardsRouteReferenceUnique<'ctx> {
                ColdShardsRouteReferenceUnique {
                    imp: self.imp.get_unique_constraint::<u16>("route_reference"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ColdShardsRouteReferenceUnique<'ctx> {
            /// Find the subscribed row whose `route_reference` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u16) -> Option<ColdShard> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ColdShard>("cold_shards");
    _table.add_unique_constraint::<u16>("route_reference", |row| &row.route_reference);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ColdShard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ColdShard>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ColdShard`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait cold_shardsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ColdShard`.
            fn cold_shards(&self) -> __sdk::__query_builder::Table<ColdShard>;
        }

        impl cold_shardsQueryTableAccess for __sdk::QueryTableAccessor {
            fn cold_shards(&self) -> __sdk::__query_builder::Table<ColdShard> {
                __sdk::__query_builder::Table::new("cold_shards")
            }
        }

