// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::definition_type::Definition;

/// Table handle for the table `definitions`.
///
/// Obtain a handle from the [`DefinitionsTableAccess::definitions`] method on [`super::RemoteTables`],
/// like `ctx.db.definitions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.definitions().on_insert(...)`.
pub struct DefinitionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Definition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `definitions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DefinitionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DefinitionsTableHandle`], which mediates access to the table `definitions`.
    fn definitions(&self) -> DefinitionsTableHandle<'_>;
}

impl DefinitionsTableAccess for super::RemoteTables {
    fn definitions(&self) -> DefinitionsTableHandle<'_> {
        DefinitionsTableHandle {
            imp: self.imp.get_table::<Definition>("definitions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DefinitionsInsertCallbackId(__sdk::CallbackId);
pub struct DefinitionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DefinitionsTableHandle<'ctx> {
    type Row = Definition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Definition> + '_ { self.imp.iter() }

    type InsertCallbackId = DefinitionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DefinitionsInsertCallbackId {
        DefinitionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DefinitionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DefinitionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DefinitionsDeleteCallbackId {
        DefinitionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DefinitionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DefinitionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DefinitionsTableHandle<'ctx> {
    type UpdateCallbackId = DefinitionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DefinitionsUpdateCallbackId {
        DefinitionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DefinitionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `definitions`,
        /// which allows point queries on the field of the same name
        /// via the [`DefinitionsIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.definitions().id().find(...)`.
        pub struct DefinitionsIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Definition, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> DefinitionsTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `definitions`.
            pub fn id(&self) -> DefinitionsIdUnique<'ctx> {
                DefinitionsIdUnique {
                    imp: self.imp.get_unique_constraint::<u32>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> DefinitionsIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<Definition> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Definition>("definitions");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Definition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Definition>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Definition`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait definitionsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Definition`.
            fn definitions(&self) -> __sdk::__query_builder::Table<Definition>;
        }

        impl definitionsQueryTableAccess for __sdk::QueryTableAccessor {
            fn definitions(&self) -> __sdk::__query_builder::Table<Definition> {
                __sdk::__query_builder::Table::new("definitions")
            }
        }

