// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetColdShardArgs {
    pub type_id: u8,
    pub region_reference: u8,
    pub shard_reference: u8,
    pub url: String,
    pub db_name: String,
}

impl From<SetColdShardArgs> for super::Reducer {
    fn from(args: SetColdShardArgs) -> Self {
        Self::SetColdShard {
            type_id: args.type_id,
            region_reference: args.region_reference,
            shard_reference: args.shard_reference,
            url: args.url,
            db_name: args.db_name,
}
}
}

impl __sdk::InModule for SetColdShardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_cold_shard`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_cold_shard {
    /// Request that the remote module invoke the reducer `set_cold_shard` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_cold_shard:set_cold_shard_then`] to run a callback after the reducer completes.
    fn set_cold_shard(&self, type_id: u8,
region_reference: u8,
shard_reference: u8,
url: String,
db_name: String,
) -> __sdk::Result<()> {
        self.set_cold_shard_then(type_id, region_reference, shard_reference, url, db_name,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_cold_shard` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_cold_shard_then(
        &self,
        type_id: u8,
region_reference: u8,
shard_reference: u8,
url: String,
db_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_cold_shard for super::RemoteReducers {
    fn set_cold_shard_then(
        &self,
        type_id: u8,
region_reference: u8,
shard_reference: u8,
url: String,
db_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetColdShardArgs { type_id, region_reference, shard_reference, url, db_name,  }, callback)
    }
}

