// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerServer {
    pub player_id: u32,
    pub server_id: u16,
    pub last_seen_ms: u64,
}


impl __sdk::InModule for PlayerServer {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `PlayerServer`.
///
/// Provides typed access to columns for query building.
pub struct PlayerServerCols {
    pub player_id: __sdk::__query_builder::Col<PlayerServer, u32>,
    pub server_id: __sdk::__query_builder::Col<PlayerServer, u16>,
    pub last_seen_ms: __sdk::__query_builder::Col<PlayerServer, u64>,
}

impl __sdk::__query_builder::HasCols for PlayerServer {
    type Cols = PlayerServerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerServerCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            server_id: __sdk::__query_builder::Col::new(table_name, "server_id"),
            last_seen_ms: __sdk::__query_builder::Col::new(table_name, "last_seen_ms"),

        }
    }
}

/// Indexed column accessor struct for the table `PlayerServer`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerServerIxCols {
    pub player_id: __sdk::__query_builder::IxCol<PlayerServer, u32>,
}

impl __sdk::__query_builder::HasIxCols for PlayerServer {
    type IxCols = PlayerServerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerServerIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerServer {}

