// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BumpArgs {
    pub to_tic: u32,
}

impl From<BumpArgs> for super::Reducer {
    fn from(args: BumpArgs) -> Self {
        Self::Bump {
            to_tic: args.to_tic,
}
}
}

impl __sdk::InModule for BumpArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bump`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bump {
    /// Request that the remote module invoke the reducer `bump` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bump:bump_then`] to run a callback after the reducer completes.
    fn bump(&self, to_tic: u32,
) -> __sdk::Result<()> {
        self.bump_then(to_tic,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `bump` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bump_then(
        &self,
        to_tic: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl bump for super::RemoteReducers {
    fn bump_then(
        &self,
        to_tic: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(BumpArgs { to_tic,  }, callback)
    }
}

