// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MovePawnArgs {
    pub now_ms: u64,
    pub object_id: u64,
    pub zone_id: u32,
    pub location: u8,
    pub rotation: u8,
    pub offset: u8,
}

impl From<MovePawnArgs> for super::Reducer {
    fn from(args: MovePawnArgs) -> Self {
        Self::MovePawn {
            now_ms: args.now_ms,
            object_id: args.object_id,
            zone_id: args.zone_id,
            location: args.location,
            rotation: args.rotation,
            offset: args.offset,
}
}
}

impl __sdk::InModule for MovePawnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_pawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_pawn {
    /// Request that the remote module invoke the reducer `move_pawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_pawn:move_pawn_then`] to run a callback after the reducer completes.
    fn move_pawn(&self, now_ms: u64,
object_id: u64,
zone_id: u32,
location: u8,
rotation: u8,
offset: u8,
) -> __sdk::Result<()> {
        self.move_pawn_then(now_ms, object_id, zone_id, location, rotation, offset,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_pawn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_pawn_then(
        &self,
        now_ms: u64,
object_id: u64,
zone_id: u32,
location: u8,
rotation: u8,
offset: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_pawn for super::RemoteReducers {
    fn move_pawn_then(
        &self,
        now_ms: u64,
object_id: u64,
zone_id: u32,
location: u8,
rotation: u8,
offset: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(MovePawnArgs { now_ms, object_id, zone_id, location, rotation, offset,  }, callback)
    }
}

