// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyHotArgs {
    pub now_ms: u64,
    pub layer: u8,
    pub zone_id: u32,
    pub locations: Vec::<u8>,
    pub rotations: Vec::<u8>,
    pub ids: Vec::<u16>,
}

impl From<ApplyHotArgs> for super::Reducer {
    fn from(args: ApplyHotArgs) -> Self {
        Self::ApplyHot {
            now_ms: args.now_ms,
            layer: args.layer,
            zone_id: args.zone_id,
            locations: args.locations,
            rotations: args.rotations,
            ids: args.ids,
}
}
}

impl __sdk::InModule for ApplyHotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_hot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_hot {
    /// Request that the remote module invoke the reducer `apply_hot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`apply_hot:apply_hot_then`] to run a callback after the reducer completes.
    fn apply_hot(&self, now_ms: u64,
layer: u8,
zone_id: u32,
locations: Vec::<u8>,
rotations: Vec::<u8>,
ids: Vec::<u16>,
) -> __sdk::Result<()> {
        self.apply_hot_then(now_ms, layer, zone_id, locations, rotations, ids,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `apply_hot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn apply_hot_then(
        &self,
        now_ms: u64,
layer: u8,
zone_id: u32,
locations: Vec::<u8>,
rotations: Vec::<u8>,
ids: Vec::<u16>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl apply_hot for super::RemoteReducers {
    fn apply_hot_then(
        &self,
        now_ms: u64,
layer: u8,
zone_id: u32,
locations: Vec::<u8>,
rotations: Vec::<u8>,
ids: Vec::<u16>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ApplyHotArgs { now_ms, layer, zone_id, locations, rotations, ids,  }, callback)
    }
}

