// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BeginReleaseArgs {
    pub now_ms: u64,
    pub zone_id: u32,
    pub location: u8,
}

impl From<BeginReleaseArgs> for super::Reducer {
    fn from(args: BeginReleaseArgs) -> Self {
        Self::BeginRelease {
            now_ms: args.now_ms,
            zone_id: args.zone_id,
            location: args.location,
}
}
}

impl __sdk::InModule for BeginReleaseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `begin_release`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait begin_release {
    /// Request that the remote module invoke the reducer `begin_release` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`begin_release:begin_release_then`] to run a callback after the reducer completes.
    fn begin_release(&self, now_ms: u64,
zone_id: u32,
location: u8,
) -> __sdk::Result<()> {
        self.begin_release_then(now_ms, zone_id, location,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `begin_release` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn begin_release_then(
        &self,
        now_ms: u64,
zone_id: u32,
location: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl begin_release for super::RemoteReducers {
    fn begin_release_then(
        &self,
        now_ms: u64,
zone_id: u32,
location: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(BeginReleaseArgs { now_ms, zone_id, location,  }, callback)
    }
}

