// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::transfer_type::Transfer;

/// Table handle for the table `transfers`.
///
/// Obtain a handle from the [`TransfersTableAccess::transfers`] method on [`super::RemoteTables`],
/// like `ctx.db.transfers()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transfers().on_insert(...)`.
pub struct TransfersTableHandle<'ctx> {
    imp: __sdk::TableHandle<Transfer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `transfers`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TransfersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TransfersTableHandle`], which mediates access to the table `transfers`.
    fn transfers(&self) -> TransfersTableHandle<'_>;
}

impl TransfersTableAccess for super::RemoteTables {
    fn transfers(&self) -> TransfersTableHandle<'_> {
        TransfersTableHandle {
            imp: self.imp.get_table::<Transfer>("transfers"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TransfersInsertCallbackId(__sdk::CallbackId);
pub struct TransfersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TransfersTableHandle<'ctx> {
    type Row = Transfer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Transfer> + '_ { self.imp.iter() }

    type InsertCallbackId = TransfersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransfersInsertCallbackId {
        TransfersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransfersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TransfersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransfersDeleteCallbackId {
        TransfersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransfersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TransfersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TransfersTableHandle<'ctx> {
    type UpdateCallbackId = TransfersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransfersUpdateCallbackId {
        TransfersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransfersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `transfer_id` unique index on the table `transfers`,
        /// which allows point queries on the field of the same name
        /// via the [`TransfersTransferIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.transfers().transfer_id().find(...)`.
        pub struct TransfersTransferIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Transfer, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> TransfersTableHandle<'ctx> {
            /// Get a handle on the `transfer_id` unique index on the table `transfers`.
            pub fn transfer_id(&self) -> TransfersTransferIdUnique<'ctx> {
                TransfersTransferIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("transfer_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> TransfersTransferIdUnique<'ctx> {
            /// Find the subscribed row whose `transfer_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Transfer> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Transfer>("transfers");
    _table.add_unique_constraint::<u64>("transfer_id", |row| &row.transfer_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Transfer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Transfer>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Transfer`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait transfersQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Transfer`.
            fn transfers(&self) -> __sdk::__query_builder::Table<Transfer>;
        }

        impl transfersQueryTableAccess for __sdk::QueryTableAccessor {
            fn transfers(&self) -> __sdk::__query_builder::Table<Transfer> {
                __sdk::__query_builder::Table::new("transfers")
            }
        }

