// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::applied_foreign_type::AppliedForeign;

/// Table handle for the table `applied_foreign`.
///
/// Obtain a handle from the [`AppliedForeignTableAccess::applied_foreign`] method on [`super::RemoteTables`],
/// like `ctx.db.applied_foreign()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.applied_foreign().on_insert(...)`.
pub struct AppliedForeignTableHandle<'ctx> {
    imp: __sdk::TableHandle<AppliedForeign>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `applied_foreign`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AppliedForeignTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AppliedForeignTableHandle`], which mediates access to the table `applied_foreign`.
    fn applied_foreign(&self) -> AppliedForeignTableHandle<'_>;
}

impl AppliedForeignTableAccess for super::RemoteTables {
    fn applied_foreign(&self) -> AppliedForeignTableHandle<'_> {
        AppliedForeignTableHandle {
            imp: self.imp.get_table::<AppliedForeign>("applied_foreign"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AppliedForeignInsertCallbackId(__sdk::CallbackId);
pub struct AppliedForeignDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AppliedForeignTableHandle<'ctx> {
    type Row = AppliedForeign;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = AppliedForeign> + '_ { self.imp.iter() }

    type InsertCallbackId = AppliedForeignInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AppliedForeignInsertCallbackId {
        AppliedForeignInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AppliedForeignInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AppliedForeignDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AppliedForeignDeleteCallbackId {
        AppliedForeignDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AppliedForeignDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AppliedForeignUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AppliedForeignTableHandle<'ctx> {
    type UpdateCallbackId = AppliedForeignUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AppliedForeignUpdateCallbackId {
        AppliedForeignUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AppliedForeignUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `applied_foreign`,
        /// which allows point queries on the field of the same name
        /// via the [`AppliedForeignIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.applied_foreign().id().find(...)`.
        pub struct AppliedForeignIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<AppliedForeign, u128>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> AppliedForeignTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `applied_foreign`.
            pub fn id(&self) -> AppliedForeignIdUnique<'ctx> {
                AppliedForeignIdUnique {
                    imp: self.imp.get_unique_constraint::<u128>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> AppliedForeignIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u128) -> Option<AppliedForeign> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<AppliedForeign>("applied_foreign");
    _table.add_unique_constraint::<u128>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AppliedForeign>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<AppliedForeign>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `AppliedForeign`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait applied_foreignQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `AppliedForeign`.
            fn applied_foreign(&self) -> __sdk::__query_builder::Table<AppliedForeign>;
        }

        impl applied_foreignQueryTableAccess for __sdk::QueryTableAccessor {
            fn applied_foreign(&self) -> __sdk::__query_builder::Table<AppliedForeign> {
                __sdk::__query_builder::Table::new("applied_foreign")
            }
        }

