// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EventLog {
    pub event_reference: u32,
    pub event_tic: u32,
    pub actions: Vec::<u64>,
    pub targets: Vec::<u64>,
    pub worker_reference: u16,
    pub status: u8,
    pub failed: bool,
    pub tic_state_change: u32,
}


impl __sdk::InModule for EventLog {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `EventLog`.
///
/// Provides typed access to columns for query building.
pub struct EventLogCols {
    pub event_reference: __sdk::__query_builder::Col<EventLog, u32>,
    pub event_tic: __sdk::__query_builder::Col<EventLog, u32>,
    pub actions: __sdk::__query_builder::Col<EventLog, Vec::<u64>>,
    pub targets: __sdk::__query_builder::Col<EventLog, Vec::<u64>>,
    pub worker_reference: __sdk::__query_builder::Col<EventLog, u16>,
    pub status: __sdk::__query_builder::Col<EventLog, u8>,
    pub failed: __sdk::__query_builder::Col<EventLog, bool>,
    pub tic_state_change: __sdk::__query_builder::Col<EventLog, u32>,
}

impl __sdk::__query_builder::HasCols for EventLog {
    type Cols = EventLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EventLogCols {
            event_reference: __sdk::__query_builder::Col::new(table_name, "event_reference"),
            event_tic: __sdk::__query_builder::Col::new(table_name, "event_tic"),
            actions: __sdk::__query_builder::Col::new(table_name, "actions"),
            targets: __sdk::__query_builder::Col::new(table_name, "targets"),
            worker_reference: __sdk::__query_builder::Col::new(table_name, "worker_reference"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            failed: __sdk::__query_builder::Col::new(table_name, "failed"),
            tic_state_change: __sdk::__query_builder::Col::new(table_name, "tic_state_change"),

        }
    }
}

/// Indexed column accessor struct for the table `EventLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct EventLogIxCols {
    pub event_reference: __sdk::__query_builder::IxCol<EventLog, u32>,
    pub event_tic: __sdk::__query_builder::IxCol<EventLog, u32>,
}

impl __sdk::__query_builder::HasIxCols for EventLog {
    type IxCols = EventLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EventLogIxCols {
            event_reference: __sdk::__query_builder::IxCol::new(table_name, "event_reference"),
            event_tic: __sdk::__query_builder::IxCol::new(table_name, "event_tic"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EventLog {}

