// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MintColdArgs {
    pub target: u64,
    pub tombstone: u16,
    pub kind: u16,
    pub zone_id: u32,
    pub location: u8,
    pub rotation: u8,
    pub offset: u8,
    pub data_0: u64,
    pub data_1: u64,
}

impl From<MintColdArgs> for super::Reducer {
    fn from(args: MintColdArgs) -> Self {
        Self::MintCold {
            target: args.target,
            tombstone: args.tombstone,
            kind: args.kind,
            zone_id: args.zone_id,
            location: args.location,
            rotation: args.rotation,
            offset: args.offset,
            data_0: args.data_0,
            data_1: args.data_1,
}
}
}

impl __sdk::InModule for MintColdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mint_cold`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mint_cold {
    /// Request that the remote module invoke the reducer `mint_cold` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`mint_cold:mint_cold_then`] to run a callback after the reducer completes.
    fn mint_cold(&self, target: u64,
tombstone: u16,
kind: u16,
zone_id: u32,
location: u8,
rotation: u8,
offset: u8,
data_0: u64,
data_1: u64,
) -> __sdk::Result<()> {
        self.mint_cold_then(target, tombstone, kind, zone_id, location, rotation, offset, data_0, data_1,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `mint_cold` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn mint_cold_then(
        &self,
        target: u64,
tombstone: u16,
kind: u16,
zone_id: u32,
location: u8,
rotation: u8,
offset: u8,
data_0: u64,
data_1: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl mint_cold for super::RemoteReducers {
    fn mint_cold_then(
        &self,
        target: u64,
tombstone: u16,
kind: u16,
zone_id: u32,
location: u8,
rotation: u8,
offset: u8,
data_0: u64,
data_1: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(MintColdArgs { target, tombstone, kind, zone_id, location, rotation, offset, data_0, data_1,  }, callback)
    }
}

