// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit aa73d1c35b4b346b98eeba10a3d756b4ae72162f).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

pub mod cold_type;
pub mod cold_removed_type;
pub mod event_log_type;
pub mod holder_type;
pub mod object_counter_type;
pub mod open_rows_type;
pub mod shard_meta_type;
pub mod state_type;
pub mod state_log_type;
pub mod target_state_type;
pub mod tic_meta_type;
pub mod abort_reducer;
pub mod append_reducer;
pub mod bump_reducer;
pub mod claim_reducer;
pub mod drop_timed_out_reducer;
pub mod mint_cold_reducer;
pub mod pack_settle_reducer;
pub mod ready_reducer;
pub mod resolve_reducer;
pub mod seed_cold_row_reducer;
pub mod seed_entity_reducer;
pub mod set_shard_id_reducer;
pub mod stand_up_reducer;
pub mod tick_gc_reducer;
pub mod cold_table;
pub mod cold_removed_table;
pub mod event_log_table;
pub mod holder_table;
pub mod open_rows_table;
pub mod shard_meta_table;
pub mod state_table;
pub mod state_log_table;
pub mod tic_meta_table;

pub use cold_type::Cold;
pub use cold_removed_type::ColdRemoved;
pub use event_log_type::EventLog;
pub use holder_type::Holder;
pub use object_counter_type::ObjectCounter;
pub use open_rows_type::OpenRows;
pub use shard_meta_type::ShardMeta;
pub use state_type::State;
pub use state_log_type::StateLog;
pub use target_state_type::TargetState;
pub use tic_meta_type::TicMeta;
pub use cold_table::*;
pub use cold_removed_table::*;
pub use event_log_table::*;
pub use holder_table::*;
pub use open_rows_table::*;
pub use shard_meta_table::*;
pub use state_table::*;
pub use state_log_table::*;
pub use tic_meta_table::*;
pub use abort_reducer::abort;
pub use append_reducer::append;
pub use bump_reducer::bump;
pub use claim_reducer::claim;
pub use drop_timed_out_reducer::drop_timed_out;
pub use mint_cold_reducer::mint_cold;
pub use pack_settle_reducer::pack_settle;
pub use ready_reducer::ready;
pub use resolve_reducer::resolve;
pub use seed_cold_row_reducer::seed_cold_row;
pub use seed_entity_reducer::seed_entity;
pub use set_shard_id_reducer::set_shard_id;
pub use stand_up_reducer::stand_up;
pub use tick_gc_reducer::tick_gc;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
        Abort {
        worker_reference: u16,
        event_reference: u64,
}    ,
    Append {
        actions: Vec::<u64>,
        targets: Vec::<u64>,
}    ,
    Bump {
        to_tic: u32,
}    ,
    Claim {
        worker_reference: u16,
        event_reference: u64,
}    ,
    DropTimedOut ,
    MintCold {
        target: u64,
        tombstone: u16,
        kind: u16,
        zone_id: u32,
        location: u8,
        rotation: u8,
        offset: u8,
        data_0: u64,
        data_1: u64,
}    ,
    PackSettle {
        entity_key: u64,
        zone_id: u32,
        type_reference: u32,
        object_kind_reference: u32,
        tombstone: u16,
}    ,
    Ready {
        worker_reference: u16,
        event_reference: u64,
}    ,
    Resolve {
        worker_reference: u16,
        event_reference: u64,
        results: Vec::<TargetState>,
}    ,
    SeedColdRow {
        zone_id: u32,
        type_reference: u32,
        kinds: Vec::<u32>,
}    ,
    SeedEntity {
        entity_key: u64,
        kind: u16,
        zone_id: u32,
        location: u8,
        rotation: u8,
        offset: u8,
        data_0: u64,
        data_1: u64,
}    ,
    SetShardId {
        shard_id: u16,
}    ,
    StandUp {
        worker_reference: u16,
        event_reference: u64,
        target: u64,
}    ,
    TickGc ,
}


impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
                        Reducer::Abort { .. } => "abort",
            Reducer::Append { .. } => "append",
            Reducer::Bump { .. } => "bump",
            Reducer::Claim { .. } => "claim",
            Reducer::DropTimedOut => "drop_timed_out",
            Reducer::MintCold { .. } => "mint_cold",
            Reducer::PackSettle { .. } => "pack_settle",
            Reducer::Ready { .. } => "ready",
            Reducer::Resolve { .. } => "resolve",
            Reducer::SeedColdRow { .. } => "seed_cold_row",
            Reducer::SeedEntity { .. } => "seed_entity",
            Reducer::SetShardId { .. } => "set_shard_id",
            Reducer::StandUp { .. } => "stand_up",
            Reducer::TickGc => "tick_gc",
            _ => unreachable!(),
}
}
    #[allow(clippy::clone_on_copy)]
fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::Abort{
                worker_reference,
                event_reference,
}             => __sats::bsatn::to_vec(&abort_reducer::AbortArgs {
                worker_reference: worker_reference.clone(),
                event_reference: event_reference.clone(),
}),
            Reducer::Append{
                actions,
                targets,
}             => __sats::bsatn::to_vec(&append_reducer::AppendArgs {
                actions: actions.clone(),
                targets: targets.clone(),
}),
            Reducer::Bump{
                to_tic,
}             => __sats::bsatn::to_vec(&bump_reducer::BumpArgs {
                to_tic: to_tic.clone(),
}),
            Reducer::Claim{
                worker_reference,
                event_reference,
}             => __sats::bsatn::to_vec(&claim_reducer::ClaimArgs {
                worker_reference: worker_reference.clone(),
                event_reference: event_reference.clone(),
}),
            Reducer::DropTimedOut => __sats::bsatn::to_vec(&drop_timed_out_reducer::DropTimedOutArgs {
                }),
Reducer::MintCold{
                target,
                tombstone,
                kind,
                zone_id,
                location,
                rotation,
                offset,
                data_0,
                data_1,
}             => __sats::bsatn::to_vec(&mint_cold_reducer::MintColdArgs {
                target: target.clone(),
                tombstone: tombstone.clone(),
                kind: kind.clone(),
                zone_id: zone_id.clone(),
                location: location.clone(),
                rotation: rotation.clone(),
                offset: offset.clone(),
                data_0: data_0.clone(),
                data_1: data_1.clone(),
}),
            Reducer::PackSettle{
                entity_key,
                zone_id,
                type_reference,
                object_kind_reference,
                tombstone,
}             => __sats::bsatn::to_vec(&pack_settle_reducer::PackSettleArgs {
                entity_key: entity_key.clone(),
                zone_id: zone_id.clone(),
                type_reference: type_reference.clone(),
                object_kind_reference: object_kind_reference.clone(),
                tombstone: tombstone.clone(),
}),
            Reducer::Ready{
                worker_reference,
                event_reference,
}             => __sats::bsatn::to_vec(&ready_reducer::ReadyArgs {
                worker_reference: worker_reference.clone(),
                event_reference: event_reference.clone(),
}),
            Reducer::Resolve{
                worker_reference,
                event_reference,
                results,
}             => __sats::bsatn::to_vec(&resolve_reducer::ResolveArgs {
                worker_reference: worker_reference.clone(),
                event_reference: event_reference.clone(),
                results: results.clone(),
}),
            Reducer::SeedColdRow{
                zone_id,
                type_reference,
                kinds,
}             => __sats::bsatn::to_vec(&seed_cold_row_reducer::SeedColdRowArgs {
                zone_id: zone_id.clone(),
                type_reference: type_reference.clone(),
                kinds: kinds.clone(),
}),
            Reducer::SeedEntity{
                entity_key,
                kind,
                zone_id,
                location,
                rotation,
                offset,
                data_0,
                data_1,
}             => __sats::bsatn::to_vec(&seed_entity_reducer::SeedEntityArgs {
                entity_key: entity_key.clone(),
                kind: kind.clone(),
                zone_id: zone_id.clone(),
                location: location.clone(),
                rotation: rotation.clone(),
                offset: offset.clone(),
                data_0: data_0.clone(),
                data_1: data_1.clone(),
}),
            Reducer::SetShardId{
                shard_id,
}             => __sats::bsatn::to_vec(&set_shard_id_reducer::SetShardIdArgs {
                shard_id: shard_id.clone(),
}),
            Reducer::StandUp{
                worker_reference,
                event_reference,
                target,
}             => __sats::bsatn::to_vec(&stand_up_reducer::StandUpArgs {
                worker_reference: worker_reference.clone(),
                event_reference: event_reference.clone(),
                target: target.clone(),
}),
            Reducer::TickGc => __sats::bsatn::to_vec(&tick_gc_reducer::TickGcArgs {
                }),
_ => unreachable!(),
}
}
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
        cold: __sdk::TableUpdate<Cold>,
    cold_removed: __sdk::TableUpdate<ColdRemoved>,
    event_log: __sdk::TableUpdate<EventLog>,
    holder: __sdk::TableUpdate<Holder>,
    open_rows: __sdk::TableUpdate<OpenRows>,
    shard_meta: __sdk::TableUpdate<ShardMeta>,
    state: __sdk::TableUpdate<State>,
    state_log: __sdk::TableUpdate<StateLog>,
    tic_meta: __sdk::TableUpdate<TicMeta>,
}


impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {

        "cold" => db_update.cold.append(cold_table::parse_table_update(table_update)?),
    "cold_removed" => db_update.cold_removed.append(cold_removed_table::parse_table_update(table_update)?),
    "event_log" => db_update.event_log.append(event_log_table::parse_table_update(table_update)?),
    "holder" => db_update.holder.append(holder_table::parse_table_update(table_update)?),
    "open_rows" => db_update.open_rows.append(open_rows_table::parse_table_update(table_update)?),
    "shard_meta" => db_update.shard_meta.append(shard_meta_table::parse_table_update(table_update)?),
    "state" => db_update.state.append(state_table::parse_table_update(table_update)?),
    "state_log" => db_update.state_log.append(state_log_table::parse_table_update(table_update)?),
    "tic_meta" => db_update.tic_meta.append(tic_meta_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    ).into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(&self, cache: &mut __sdk::ClientCache<RemoteModule>) -> AppliedDiff<'_> {
                    let mut diff = AppliedDiff::default();
                
                diff.cold = cache.apply_diff_to_table::<Cold>("cold", &self.cold).with_updates_by_pk(|row| &row.cold_key);
        diff.cold_removed = cache.apply_diff_to_table::<ColdRemoved>("cold_removed", &self.cold_removed).with_updates_by_pk(|row| &row.zone_key);
        diff.event_log = cache.apply_diff_to_table::<EventLog>("event_log", &self.event_log).with_updates_by_pk(|row| &row.event_reference);
        diff.holder = cache.apply_diff_to_table::<Holder>("holder", &self.holder).with_updates_by_pk(|row| &row.id);
        diff.open_rows = cache.apply_diff_to_table::<OpenRows>("open_rows", &self.open_rows).with_updates_by_pk(|row| &row.id);
        diff.shard_meta = cache.apply_diff_to_table::<ShardMeta>("shard_meta", &self.shard_meta).with_updates_by_pk(|row| &row.id);
        diff.state = cache.apply_diff_to_table::<State>("state", &self.state).with_updates_by_pk(|row| &row.entity_key);
        diff.state_log = cache.apply_diff_to_table::<StateLog>("state_log", &self.state_log).with_updates_by_pk(|row| &row.id);
        diff.tic_meta = cache.apply_diff_to_table::<TicMeta>("tic_meta", &self.tic_meta).with_updates_by_pk(|row| &row.id);

                    diff
                }
fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "cold" => db_update.cold.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cold_removed" => db_update.cold_removed.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "event_log" => db_update.event_log.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "holder" => db_update.holder.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "open_rows" => db_update.open_rows.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "shard_meta" => db_update.shard_meta.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "state" => db_update.state.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "state_log" => db_update.state_log.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tic_meta" => db_update.tic_meta.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "cold" => db_update.cold.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cold_removed" => db_update.cold_removed.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "event_log" => db_update.event_log.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "holder" => db_update.holder.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "open_rows" => db_update.open_rows.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "shard_meta" => db_update.shard_meta.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "state" => db_update.state.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "state_log" => db_update.state_log.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tic_meta" => db_update.tic_meta.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
        cold: __sdk::TableAppliedDiff<'r, Cold>,
    cold_removed: __sdk::TableAppliedDiff<'r, ColdRemoved>,
    event_log: __sdk::TableAppliedDiff<'r, EventLog>,
    holder: __sdk::TableAppliedDiff<'r, Holder>,
    open_rows: __sdk::TableAppliedDiff<'r, OpenRows>,
    shard_meta: __sdk::TableAppliedDiff<'r, ShardMeta>,
    state: __sdk::TableAppliedDiff<'r, State>,
    state_log: __sdk::TableAppliedDiff<'r, StateLog>,
    tic_meta: __sdk::TableAppliedDiff<'r, TicMeta>,
    __unused: std::marker::PhantomData<&'r ()>,
}


impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(&self, event: &EventContext, callbacks: &mut __sdk::DbCallbacks<RemoteModule>) {
                callbacks.invoke_table_row_callbacks::<Cold>("cold", &self.cold, event);
        callbacks.invoke_table_row_callbacks::<ColdRemoved>("cold_removed", &self.cold_removed, event);
        callbacks.invoke_table_row_callbacks::<EventLog>("event_log", &self.event_log, event);
        callbacks.invoke_table_row_callbacks::<Holder>("holder", &self.holder, event);
        callbacks.invoke_table_row_callbacks::<OpenRows>("open_rows", &self.open_rows, event);
        callbacks.invoke_table_row_callbacks::<ShardMeta>("shard_meta", &self.shard_meta, event);
        callbacks.invoke_table_row_callbacks::<State>("state", &self.state, event);
        callbacks.invoke_table_row_callbacks::<StateLog>("state_log", &self.state_log, event);
        callbacks.invoke_table_row_callbacks::<TicMeta>("tic_meta", &self.tic_meta, event);
}
}


#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(target_arch = "wasm32", doc = "- [`DbConnection::run_background_task`].")]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(not(target_arch =  "wasm32"), doc = "- [`DbConnection::advance_one_message_blocking`].")]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }

}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
> {}
impl<Ctx: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>> RemoteDbContext for Ctx {}


/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
                cold_table::register_table(client_cache);
        cold_removed_table::register_table(client_cache);
        event_log_table::register_table(client_cache);
        holder_table::register_table(client_cache);
        open_rows_table::register_table(client_cache);
        shard_meta_table::register_table(client_cache);
        state_table::register_table(client_cache);
        state_log_table::register_table(client_cache);
        tic_meta_table::register_table(client_cache);
}
const ALL_TABLE_NAMES: &'static [&'static str] = &[
                "cold",
        "cold_removed",
        "event_log",
        "holder",
        "open_rows",
        "shard_meta",
        "state",
        "state_log",
        "tic_meta",
];
}
