// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StandUpArgs {
    pub worker_reference: u16,
    pub event_reference: u32,
    pub target: u64,
}

impl From<StandUpArgs> for super::Reducer {
    fn from(args: StandUpArgs) -> Self {
        Self::StandUp {
            worker_reference: args.worker_reference,
            event_reference: args.event_reference,
            target: args.target,
}
}
}

impl __sdk::InModule for StandUpArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stand_up`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stand_up {
    /// Request that the remote module invoke the reducer `stand_up` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stand_up:stand_up_then`] to run a callback after the reducer completes.
    fn stand_up(&self, worker_reference: u16,
event_reference: u32,
target: u64,
) -> __sdk::Result<()> {
        self.stand_up_then(worker_reference, event_reference, target,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `stand_up` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stand_up_then(
        &self,
        worker_reference: u16,
event_reference: u32,
target: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl stand_up for super::RemoteReducers {
    fn stand_up_then(
        &self,
        worker_reference: u16,
event_reference: u32,
target: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(StandUpArgs { worker_reference, event_reference, target,  }, callback)
    }
}

