// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveDebugMoverArgs {
    pub now: u64,
    pub dest_gx: i32,
    pub dest_gy: i32,
}

impl From<MoveDebugMoverArgs> for super::Reducer {
    fn from(args: MoveDebugMoverArgs) -> Self {
        Self::MoveDebugMover {
            now: args.now,
            dest_gx: args.dest_gx,
            dest_gy: args.dest_gy,
}
}
}

impl __sdk::InModule for MoveDebugMoverArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_debug_mover`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_debug_mover {
    /// Request that the remote module invoke the reducer `move_debug_mover` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_debug_mover:move_debug_mover_then`] to run a callback after the reducer completes.
    fn move_debug_mover(&self, now: u64,
dest_gx: i32,
dest_gy: i32,
) -> __sdk::Result<()> {
        self.move_debug_mover_then(now, dest_gx, dest_gy,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_debug_mover` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_debug_mover_then(
        &self,
        now: u64,
dest_gx: i32,
dest_gy: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_debug_mover for super::RemoteReducers {
    fn move_debug_mover_then(
        &self,
        now: u64,
dest_gx: i32,
dest_gy: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(MoveDebugMoverArgs { now, dest_gx, dest_gy,  }, callback)
    }
}

