// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetPawnDataArgs {
    pub now_ms: u64,
    pub object_id: u64,
    pub data: Vec::<u64>,
}

impl From<SetPawnDataArgs> for super::Reducer {
    fn from(args: SetPawnDataArgs) -> Self {
        Self::SetPawnData {
            now_ms: args.now_ms,
            object_id: args.object_id,
            data: args.data,
}
}
}

impl __sdk::InModule for SetPawnDataArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_pawn_data`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_pawn_data {
    /// Request that the remote module invoke the reducer `set_pawn_data` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_pawn_data:set_pawn_data_then`] to run a callback after the reducer completes.
    fn set_pawn_data(&self, now_ms: u64,
object_id: u64,
data: Vec::<u64>,
) -> __sdk::Result<()> {
        self.set_pawn_data_then(now_ms, object_id, data,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_pawn_data` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_pawn_data_then(
        &self,
        now_ms: u64,
object_id: u64,
data: Vec::<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_pawn_data for super::RemoteReducers {
    fn set_pawn_data_then(
        &self,
        now_ms: u64,
object_id: u64,
data: Vec::<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetPawnDataArgs { now_ms, object_id, data,  }, callback)
    }
}

