// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnPawnArgs {
    pub now_ms: u64,
    pub owner_id: u32,
    pub zone_id: u32,
    pub location: u8,
    pub rotation: u8,
    pub id: u16,
    pub offset: u8,
    pub data: Vec::<u64>,
}

impl From<SpawnPawnArgs> for super::Reducer {
    fn from(args: SpawnPawnArgs) -> Self {
        Self::SpawnPawn {
            now_ms: args.now_ms,
            owner_id: args.owner_id,
            zone_id: args.zone_id,
            location: args.location,
            rotation: args.rotation,
            id: args.id,
            offset: args.offset,
            data: args.data,
}
}
}

impl __sdk::InModule for SpawnPawnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_pawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_pawn {
    /// Request that the remote module invoke the reducer `spawn_pawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_pawn:spawn_pawn_then`] to run a callback after the reducer completes.
    fn spawn_pawn(&self, now_ms: u64,
owner_id: u32,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,
data: Vec::<u64>,
) -> __sdk::Result<()> {
        self.spawn_pawn_then(now_ms, owner_id, zone_id, location, rotation, id, offset, data,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_pawn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_pawn_then(
        &self,
        now_ms: u64,
owner_id: u32,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,
data: Vec::<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_pawn for super::RemoteReducers {
    fn spawn_pawn_then(
        &self,
        now_ms: u64,
owner_id: u32,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,
data: Vec::<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SpawnPawnArgs { now_ms, owner_id, zone_id, location, rotation, id, offset, data,  }, callback)
    }
}

