; content/visual/manifest/biome-thing.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust_world/textures/biome-thing/ (all kind leaves, any depth).
; Existence index for the (future) `^r2` resolver: per type &subcategories; per KIND
; LEAF a :<key> (leaf path below the type, so <type>/<key> = the client stem) carrying
; &variant (variations), &layers (layer count), &subkinds (override ints), &hash
; (master version), &maps (bit0 albedo|bit1 normal|bit2 emissive). The filename
; layer/variant default to 0/1. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::biome-thing>
    @define>
        0 &subcategories array
    :default/berry>
      @define>
        1 &layers set
        70749754790028 &hash set
        3 &maps set
        12 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        12 &var_variant array
        0 &var_variant.0 set
        1 &var_variant.1 set
        2 &var_variant.2 set
        3 &var_variant.3 set
        4 &var_variant.4 set
        5 &var_variant.5 set
        6 &var_variant.6 set
        7 &var_variant.7 set
        8 &var_variant.8 set
        9 &var_variant.9 set
        10 &var_variant.10 set
        11 &var_variant.11 set
        1 &part_id array
        0 &part_id.0 set
        1 &part_variants array
        12 &part_variants.0 set
        0 &subkinds array
    :default/conifer>
      @define>
        1 &layers set
        3424400179522492 &hash set
        3 &maps set
        9 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        9 &var_variant array
        0 &var_variant.0 set
        1 &var_variant.1 set
        2 &var_variant.2 set
        3 &var_variant.3 set
        4 &var_variant.4 set
        5 &var_variant.5 set
        6 &var_variant.6 set
        7 &var_variant.7 set
        8 &var_variant.8 set
        1 &part_id array
        0 &part_id.0 set
        1 &part_variants array
        9 &part_variants.0 set
        0 &subkinds array
    :default/flora>
      @define>
        1 &layers set
        3890346443754983 &hash set
        3 &maps set
        13 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        13 &var_variant array
        0 &var_variant.0 set
        1 &var_variant.1 set
        2 &var_variant.2 set
        3 &var_variant.3 set
        4 &var_variant.4 set
        5 &var_variant.5 set
        6 &var_variant.6 set
        7 &var_variant.7 set
        8 &var_variant.8 set
        9 &var_variant.9 set
        10 &var_variant.10 set
        11 &var_variant.11 set
        12 &var_variant.12 set
        1 &part_id array
        0 &part_id.0 set
        1 &part_variants array
        13 &part_variants.0 set
        0 &subkinds array
