; content/visual/manifest/linked.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust_world/textures/master/linked.<biome>/<object>.<faction>/.
; Existence index for the `^r2` resolver: per category &biomes; per base
; object &count (variations), &parts (layers), &factions (override ints),
; &hash (master version), &maps (bit0 albedo|bit1 normal|bit2 emissive).
; The .0 base of every axis (biome/faction/part) is implicit. Do not edit
; by hand — re-run `bin/art manifest`.

<manifest>
  ::linked>
    @define>
        0 &biomes array
    :wall_blueprint>
      @define>
        1 &parts set
        2900814445882459 &hash set
        0 &maps set
        16 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        1 &var_id.13 set
        1 &var_id.14 set
        1 &var_id.15 set
        16 &var_count array
        1 &var_count.0 set
        2 &var_count.1 set
        3 &var_count.2 set
        4 &var_count.3 set
        5 &var_count.4 set
        6 &var_count.5 set
        7 &var_count.6 set
        8 &var_count.7 set
        9 &var_count.8 set
        10 &var_count.9 set
        11 &var_count.10 set
        12 &var_count.11 set
        13 &var_count.12 set
        14 &var_count.13 set
        15 &var_count.14 set
        16 &var_count.15 set
        0 &factions array
    :wall_smooth>
      @define>
        1 &parts set
        2714352114987274 &hash set
        3 &maps set
        3 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        3 &var_count array
        1 &var_count.0 set
        10 &var_count.1 set
        11 &var_count.2 set
        0 &factions array
