; content/visual/manifest/pawn.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust_world/textures/pawn/ (all kind leaves, any depth).
; Existence index for the (future) `^r2` resolver: per type &subcategories; per KIND
; LEAF a :<key> (leaf path below the type, so <type>/<key> = the client stem) carrying
; &variant (variations), &layers (layer count), &subkinds (override ints), &hash
; (master version), &maps (bit0 albedo|bit1 normal|bit2 emissive). The filename
; layer/variant default to 0/1. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::pawn>
    @define>
        0 &subcategories array
    :animal/wolf/default>
      @define>
        1 &layers set
        862905571293901 &hash set
        7 &maps set
        7 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        7 &var_variant array
        1 &var_variant.0 set
        124 &var_variant.1 set
        125 &var_variant.2 set
        555 &var_variant.3 set
        777 &var_variant.4 set
        888 &var_variant.5 set
        1682748910 &var_variant.6 set
        0 &subkinds array
    :human/male/average>
      @define>
        2 &layers set
        3547628401840318 &hash set
        3 &maps set
        3 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        3 &var_variant array
        0 &var_variant.0 set
        1 &var_variant.1 set
        2 &var_variant.2 set
        0 &subkinds array
    :human/male/fat>
      @define>
        2 &layers set
        3054765214506445 &hash set
        3 &maps set
        3 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        3 &var_variant array
        0 &var_variant.0 set
        1 &var_variant.1 set
        2 &var_variant.2 set
        0 &subkinds array
    :human/male/fit>
      @define>
        2 &layers set
        431164441606738 &hash set
        3 &maps set
        3 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        3 &var_variant array
        0 &var_variant.0 set
        1 &var_variant.1 set
        2 &var_variant.2 set
        0 &subkinds array
