; content/visual/manifest/pawn.rd
; GENERATED by `bin/art manifest` from /home/wolf/resonantdust_world/textures/pawn/ (all kind leaves, any depth).
; Existence index for the (future) `^r2` resolver: per type &subcategories; per KIND
; LEAF a :<key> (leaf path below the type, so <type>/<key> = the client stem) carrying
; &variant (variations), &layers (layer count), &subkinds (override ints), &hash
; (master version), &maps (bit0 albedo|bit1 normal|bit2 emissive). The filename
; layer/variant default to 0/1. Do not edit by hand — re-run `bin/art manifest`.

<manifest>
  ::pawn>
    @define>
        0 &subcategories array
    :animal/wolf>
      @define>
        1 &layers set
        380912235706756 &hash set
        7 &maps set
        15 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        1 &var_id.13 set
        1 &var_id.14 set
        15 &var_variant array
        1 &var_variant.0 set
        124 &var_variant.1 set
        125 &var_variant.2 set
        555 &var_variant.3 set
        777 &var_variant.4 set
        888 &var_variant.5 set
        7001 &var_variant.6 set
        7002 &var_variant.7 set
        8101 &var_variant.8 set
        8102 &var_variant.9 set
        8201 &var_variant.10 set
        8202 &var_variant.11 set
        8301 &var_variant.12 set
        8302 &var_variant.13 set
        1682748910 &var_variant.14 set
        1 &part_id array
        0 &part_id.0 set
        1 &part_variants array
        15 &part_variants.0 set
        0 &subkinds array
    :human/female>
      @define>
        2 &layers set
        2397673015182301 &hash set
        3 &maps set
        16 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        1 &var_id.13 set
        1 &var_id.14 set
        1 &var_id.15 set
        16 &var_variant array
        0 &var_variant.0 set
        1 &var_variant.1 set
        2 &var_variant.2 set
        3 &var_variant.3 set
        4 &var_variant.4 set
        5 &var_variant.5 set
        6 &var_variant.6 set
        7 &var_variant.7 set
        8 &var_variant.8 set
        9 &var_variant.9 set
        10 &var_variant.10 set
        11 &var_variant.11 set
        12 &var_variant.12 set
        13 &var_variant.13 set
        14 &var_variant.14 set
        15 &var_variant.15 set
        2 &part_id array
        0 &part_id.0 set
        1 &part_id.1 set
        2 &part_variants array
        9 &part_variants.0 set
        16 &part_variants.1 set
        0 &subkinds array
    :human/male>
      @define>
        2 &layers set
        1489279559511702 &hash set
        3 &maps set
        16 &var_id array
        1 &var_id.0 set
        1 &var_id.1 set
        1 &var_id.2 set
        1 &var_id.3 set
        1 &var_id.4 set
        1 &var_id.5 set
        1 &var_id.6 set
        1 &var_id.7 set
        1 &var_id.8 set
        1 &var_id.9 set
        1 &var_id.10 set
        1 &var_id.11 set
        1 &var_id.12 set
        1 &var_id.13 set
        1 &var_id.14 set
        1 &var_id.15 set
        16 &var_variant array
        0 &var_variant.0 set
        1 &var_variant.1 set
        2 &var_variant.2 set
        3 &var_variant.3 set
        4 &var_variant.4 set
        5 &var_variant.5 set
        6 &var_variant.6 set
        7 &var_variant.7 set
        8 &var_variant.8 set
        9 &var_variant.9 set
        10 &var_variant.10 set
        11 &var_variant.11 set
        12 &var_variant.12 set
        13 &var_variant.13 set
        14 &var_variant.14 set
        15 &var_variant.15 set
        2 &part_id array
        0 &part_id.0 set
        1 &part_id.1 set
        2 &part_variants array
        9 &part_variants.0 set
        16 &part_variants.1 set
        0 &subkinds array
