// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlacePawnArgs {
    pub now_ms: u64,
    pub object_id: u64,
    pub owner_id: u32,
    pub zone_id: u32,
    pub location: u8,
    pub rotation: u8,
    pub id: u16,
    pub offset: u8,
    pub data: Vec::<u64>,
}

impl From<PlacePawnArgs> for super::Reducer {
    fn from(args: PlacePawnArgs) -> Self {
        Self::PlacePawn {
            now_ms: args.now_ms,
            object_id: args.object_id,
            owner_id: args.owner_id,
            zone_id: args.zone_id,
            location: args.location,
            rotation: args.rotation,
            id: args.id,
            offset: args.offset,
            data: args.data,
}
}
}

impl __sdk::InModule for PlacePawnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_pawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_pawn {
    /// Request that the remote module invoke the reducer `place_pawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_pawn:place_pawn_then`] to run a callback after the reducer completes.
    fn place_pawn(&self, now_ms: u64,
object_id: u64,
owner_id: u32,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,
data: Vec::<u64>,
) -> __sdk::Result<()> {
        self.place_pawn_then(now_ms, object_id, owner_id, zone_id, location, rotation, id, offset, data,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_pawn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_pawn_then(
        &self,
        now_ms: u64,
object_id: u64,
owner_id: u32,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,
data: Vec::<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_pawn for super::RemoteReducers {
    fn place_pawn_then(
        &self,
        now_ms: u64,
object_id: u64,
owner_id: u32,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,
data: Vec::<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PlacePawnArgs { now_ms, object_id, owner_id, zone_id, location, rotation, id, offset, data,  }, callback)
    }
}

