// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReceiveArgs {
    pub now_ms: u64,
    pub transfer_id: u64,
    pub zone_id: u32,
    pub location: u8,
    pub rotation: u8,
    pub id: u16,
}

impl From<ReceiveArgs> for super::Reducer {
    fn from(args: ReceiveArgs) -> Self {
        Self::Receive {
            now_ms: args.now_ms,
            transfer_id: args.transfer_id,
            zone_id: args.zone_id,
            location: args.location,
            rotation: args.rotation,
            id: args.id,
}
}
}

impl __sdk::InModule for ReceiveArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `receive`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait receive {
    /// Request that the remote module invoke the reducer `receive` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`receive:receive_then`] to run a callback after the reducer completes.
    fn receive(&self, now_ms: u64,
transfer_id: u64,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
) -> __sdk::Result<()> {
        self.receive_then(now_ms, transfer_id, zone_id, location, rotation, id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `receive` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn receive_then(
        &self,
        now_ms: u64,
transfer_id: u64,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl receive for super::RemoteReducers {
    fn receive_then(
        &self,
        now_ms: u64,
transfer_id: u64,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ReceiveArgs { now_ms, transfer_id, zone_id, location, rotation, id,  }, callback)
    }
}

