// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InvAddArgs {
    pub worker: u8,
    pub tic: u16,
    pub entity_reference: u32,
    pub item: u32,
}

impl From<InvAddArgs> for super::Reducer {
    fn from(args: InvAddArgs) -> Self {
        Self::InvAdd {
            worker: args.worker,
            tic: args.tic,
            entity_reference: args.entity_reference,
            item: args.item,
}
}
}

impl __sdk::InModule for InvAddArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `inv_add`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait inv_add {
    /// Request that the remote module invoke the reducer `inv_add` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`inv_add:inv_add_then`] to run a callback after the reducer completes.
    fn inv_add(&self, worker: u8,
tic: u16,
entity_reference: u32,
item: u32,
) -> __sdk::Result<()> {
        self.inv_add_then(worker, tic, entity_reference, item,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `inv_add` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn inv_add_then(
        &self,
        worker: u8,
tic: u16,
entity_reference: u32,
item: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl inv_add for super::RemoteReducers {
    fn inv_add_then(
        &self,
        worker: u8,
tic: u16,
entity_reference: u32,
item: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(InvAddArgs { worker, tic, entity_reference, item,  }, callback)
    }
}

