// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::payload_type::Payload;

/// Table handle for the table `payload`.
///
/// Obtain a handle from the [`PayloadTableAccess::payload`] method on [`super::RemoteTables`],
/// like `ctx.db.payload()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.payload().on_insert(...)`.
pub struct PayloadTableHandle<'ctx> {
    imp: __sdk::TableHandle<Payload>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `payload`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PayloadTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PayloadTableHandle`], which mediates access to the table `payload`.
    fn payload(&self) -> PayloadTableHandle<'_>;
}

impl PayloadTableAccess for super::RemoteTables {
    fn payload(&self) -> PayloadTableHandle<'_> {
        PayloadTableHandle {
            imp: self.imp.get_table::<Payload>("payload"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PayloadInsertCallbackId(__sdk::CallbackId);
pub struct PayloadDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PayloadTableHandle<'ctx> {
    type Row = Payload;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Payload> + '_ { self.imp.iter() }

    type InsertCallbackId = PayloadInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PayloadInsertCallbackId {
        PayloadInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PayloadInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PayloadDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PayloadDeleteCallbackId {
        PayloadDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PayloadDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PayloadUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PayloadTableHandle<'ctx> {
    type UpdateCallbackId = PayloadUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PayloadUpdateCallbackId {
        PayloadUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PayloadUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `entity_reference` unique index on the table `payload`,
        /// which allows point queries on the field of the same name
        /// via the [`PayloadEntityReferenceUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.payload().entity_reference().find(...)`.
        pub struct PayloadEntityReferenceUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Payload, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> PayloadTableHandle<'ctx> {
            /// Get a handle on the `entity_reference` unique index on the table `payload`.
            pub fn entity_reference(&self) -> PayloadEntityReferenceUnique<'ctx> {
                PayloadEntityReferenceUnique {
                    imp: self.imp.get_unique_constraint::<u32>("entity_reference"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> PayloadEntityReferenceUnique<'ctx> {
            /// Find the subscribed row whose `entity_reference` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<Payload> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Payload>("payload");
    _table.add_unique_constraint::<u32>("entity_reference", |row| &row.entity_reference);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Payload>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Payload>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Payload`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait payloadQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Payload`.
            fn payload(&self) -> __sdk::__query_builder::Table<Payload>;
        }

        impl payloadQueryTableAccess for __sdk::QueryTableAccessor {
            fn payload(&self) -> __sdk::__query_builder::Table<Payload> {
                __sdk::__query_builder::Table::new("payload")
            }
        }

