// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnArgs {
    pub worker: u8,
    pub tic: u16,
    pub event_reference: u32,
    pub index: u16,
    pub definition_reference: u32,
    pub position_reference: u32,
    pub payload: Vec::<u32>,
    pub needs: Vec::<u64>,
    pub data: u8,
    pub promote: bool,
    pub issuer_player_id: u32,
}

impl From<SpawnArgs> for super::Reducer {
    fn from(args: SpawnArgs) -> Self {
        Self::Spawn {
            worker: args.worker,
            tic: args.tic,
            event_reference: args.event_reference,
            index: args.index,
            definition_reference: args.definition_reference,
            position_reference: args.position_reference,
            payload: args.payload,
            needs: args.needs,
            data: args.data,
            promote: args.promote,
            issuer_player_id: args.issuer_player_id,
}
}
}

impl __sdk::InModule for SpawnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn {
    /// Request that the remote module invoke the reducer `spawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn:spawn_then`] to run a callback after the reducer completes.
    fn spawn(&self, worker: u8,
tic: u16,
event_reference: u32,
index: u16,
definition_reference: u32,
position_reference: u32,
payload: Vec::<u32>,
needs: Vec::<u64>,
data: u8,
promote: bool,
issuer_player_id: u32,
) -> __sdk::Result<()> {
        self.spawn_then(worker, tic, event_reference, index, definition_reference, position_reference, payload, needs, data, promote, issuer_player_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_then(
        &self,
        worker: u8,
tic: u16,
event_reference: u32,
index: u16,
definition_reference: u32,
position_reference: u32,
payload: Vec::<u32>,
needs: Vec::<u64>,
data: u8,
promote: bool,
issuer_player_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn for super::RemoteReducers {
    fn spawn_then(
        &self,
        worker: u8,
tic: u16,
event_reference: u32,
index: u16,
definition_reference: u32,
position_reference: u32,
payload: Vec::<u32>,
needs: Vec::<u64>,
data: u8,
promote: bool,
issuer_player_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SpawnArgs { worker, tic, event_reference, index, definition_reference, position_reference, payload, needs, data, promote, issuer_player_id,  }, callback)
    }
}

