// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ColdRemoved {
    pub zone_key: u32,
    pub removed: Vec::<u16>,
    pub version: u32,
}


impl __sdk::InModule for ColdRemoved {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ColdRemoved`.
///
/// Provides typed access to columns for query building.
pub struct ColdRemovedCols {
    pub zone_key: __sdk::__query_builder::Col<ColdRemoved, u32>,
    pub removed: __sdk::__query_builder::Col<ColdRemoved, Vec::<u16>>,
    pub version: __sdk::__query_builder::Col<ColdRemoved, u32>,
}

impl __sdk::__query_builder::HasCols for ColdRemoved {
    type Cols = ColdRemovedCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ColdRemovedCols {
            zone_key: __sdk::__query_builder::Col::new(table_name, "zone_key"),
            removed: __sdk::__query_builder::Col::new(table_name, "removed"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),

        }
    }
}

/// Indexed column accessor struct for the table `ColdRemoved`.
///
/// Provides typed access to indexed columns for query building.
pub struct ColdRemovedIxCols {
    pub zone_key: __sdk::__query_builder::IxCol<ColdRemoved, u32>,
}

impl __sdk::__query_builder::HasIxCols for ColdRemoved {
    type IxCols = ColdRemovedIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ColdRemovedIxCols {
            zone_key: __sdk::__query_builder::IxCol::new(table_name, "zone_key"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ColdRemoved {}

