// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Holder {
    pub id: u64,
    pub state_log_id: u64,
    pub event_reference: u32,
    pub source_shard: u16,
    pub kind: u8,
}


impl __sdk::InModule for Holder {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Holder`.
///
/// Provides typed access to columns for query building.
pub struct HolderCols {
    pub id: __sdk::__query_builder::Col<Holder, u64>,
    pub state_log_id: __sdk::__query_builder::Col<Holder, u64>,
    pub event_reference: __sdk::__query_builder::Col<Holder, u32>,
    pub source_shard: __sdk::__query_builder::Col<Holder, u16>,
    pub kind: __sdk::__query_builder::Col<Holder, u8>,
}

impl __sdk::__query_builder::HasCols for Holder {
    type Cols = HolderCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HolderCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            state_log_id: __sdk::__query_builder::Col::new(table_name, "state_log_id"),
            event_reference: __sdk::__query_builder::Col::new(table_name, "event_reference"),
            source_shard: __sdk::__query_builder::Col::new(table_name, "source_shard"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),

        }
    }
}

/// Indexed column accessor struct for the table `Holder`.
///
/// Provides typed access to indexed columns for query building.
pub struct HolderIxCols {
    pub event_reference: __sdk::__query_builder::IxCol<Holder, u32>,
    pub id: __sdk::__query_builder::IxCol<Holder, u64>,
    pub state_log_id: __sdk::__query_builder::IxCol<Holder, u64>,
}

impl __sdk::__query_builder::HasIxCols for Holder {
    type IxCols = HolderIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HolderIxCols {
            event_reference: __sdk::__query_builder::IxCol::new(table_name, "event_reference"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            state_log_id: __sdk::__query_builder::IxCol::new(table_name, "state_log_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Holder {}

