// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PackSettleArgs {
    pub entity_key: u64,
    pub cold_row_reference: u64,
    pub macro_position: u16,
    pub type_reference: u16,
    pub layer_id: u8,
    pub kind_pos_reference: u32,
    pub tombstone: u8,
}

impl From<PackSettleArgs> for super::Reducer {
    fn from(args: PackSettleArgs) -> Self {
        Self::PackSettle {
            entity_key: args.entity_key,
            cold_row_reference: args.cold_row_reference,
            macro_position: args.macro_position,
            type_reference: args.type_reference,
            layer_id: args.layer_id,
            kind_pos_reference: args.kind_pos_reference,
            tombstone: args.tombstone,
}
}
}

impl __sdk::InModule for PackSettleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pack_settle`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pack_settle {
    /// Request that the remote module invoke the reducer `pack_settle` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pack_settle:pack_settle_then`] to run a callback after the reducer completes.
    fn pack_settle(&self, entity_key: u64,
cold_row_reference: u64,
macro_position: u16,
type_reference: u16,
layer_id: u8,
kind_pos_reference: u32,
tombstone: u8,
) -> __sdk::Result<()> {
        self.pack_settle_then(entity_key, cold_row_reference, macro_position, type_reference, layer_id, kind_pos_reference, tombstone,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `pack_settle` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pack_settle_then(
        &self,
        entity_key: u64,
cold_row_reference: u64,
macro_position: u16,
type_reference: u16,
layer_id: u8,
kind_pos_reference: u32,
tombstone: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl pack_settle for super::RemoteReducers {
    fn pack_settle_then(
        &self,
        entity_key: u64,
cold_row_reference: u64,
macro_position: u16,
type_reference: u16,
layer_id: u8,
kind_pos_reference: u32,
tombstone: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PackSettleArgs { entity_key, cold_row_reference, macro_position, type_reference, layer_id, kind_pos_reference, tombstone,  }, callback)
    }
}

