// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicMeta {
    pub id: u8,
    pub master_tic: u32,
    pub paused: bool,
}


impl __sdk::InModule for TicMeta {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `TicMeta`.
///
/// Provides typed access to columns for query building.
pub struct TicMetaCols {
    pub id: __sdk::__query_builder::Col<TicMeta, u8>,
    pub master_tic: __sdk::__query_builder::Col<TicMeta, u32>,
    pub paused: __sdk::__query_builder::Col<TicMeta, bool>,
}

impl __sdk::__query_builder::HasCols for TicMeta {
    type Cols = TicMetaCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicMetaCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            master_tic: __sdk::__query_builder::Col::new(table_name, "master_tic"),
            paused: __sdk::__query_builder::Col::new(table_name, "paused"),

        }
    }
}

/// Indexed column accessor struct for the table `TicMeta`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicMetaIxCols {
    pub id: __sdk::__query_builder::IxCol<TicMeta, u8>,
}

impl __sdk::__query_builder::HasIxCols for TicMeta {
    type IxCols = TicMetaIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicMetaIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicMeta {}

