// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::region_shard_type::RegionShard;

/// Table handle for the table `region_shards`.
///
/// Obtain a handle from the [`RegionShardsTableAccess::region_shards`] method on [`super::RemoteTables`],
/// like `ctx.db.region_shards()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.region_shards().on_insert(...)`.
pub struct RegionShardsTableHandle<'ctx> {
    imp: __sdk::TableHandle<RegionShard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `region_shards`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RegionShardsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RegionShardsTableHandle`], which mediates access to the table `region_shards`.
    fn region_shards(&self) -> RegionShardsTableHandle<'_>;
}

impl RegionShardsTableAccess for super::RemoteTables {
    fn region_shards(&self) -> RegionShardsTableHandle<'_> {
        RegionShardsTableHandle {
            imp: self.imp.get_table::<RegionShard>("region_shards"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RegionShardsInsertCallbackId(__sdk::CallbackId);
pub struct RegionShardsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RegionShardsTableHandle<'ctx> {
    type Row = RegionShard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = RegionShard> + '_ { self.imp.iter() }

    type InsertCallbackId = RegionShardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegionShardsInsertCallbackId {
        RegionShardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RegionShardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RegionShardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegionShardsDeleteCallbackId {
        RegionShardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RegionShardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RegionShardsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RegionShardsTableHandle<'ctx> {
    type UpdateCallbackId = RegionShardsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RegionShardsUpdateCallbackId {
        RegionShardsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RegionShardsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `region_id` unique index on the table `region_shards`,
        /// which allows point queries on the field of the same name
        /// via the [`RegionShardsRegionIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.region_shards().region_id().find(...)`.
        pub struct RegionShardsRegionIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<RegionShard, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> RegionShardsTableHandle<'ctx> {
            /// Get a handle on the `region_id` unique index on the table `region_shards`.
            pub fn region_id(&self) -> RegionShardsRegionIdUnique<'ctx> {
                RegionShardsRegionIdUnique {
                    imp: self.imp.get_unique_constraint::<u32>("region_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> RegionShardsRegionIdUnique<'ctx> {
            /// Find the subscribed row whose `region_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<RegionShard> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<RegionShard>("region_shards");
    _table.add_unique_constraint::<u32>("region_id", |row| &row.region_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RegionShard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<RegionShard>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `RegionShard`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait region_shardsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `RegionShard`.
            fn region_shards(&self) -> __sdk::__query_builder::Table<RegionShard>;
        }

        impl region_shardsQueryTableAccess for __sdk::QueryTableAccessor {
            fn region_shards(&self) -> __sdk::__query_builder::Table<RegionShard> {
                __sdk::__query_builder::Table::new("region_shards")
            }
        }

