// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnObjectArgs {
    pub obj_type: u8,
    pub zone_id: u32,
    pub tiles: Vec::<u8>,
}

impl From<SpawnObjectArgs> for super::Reducer {
    fn from(args: SpawnObjectArgs) -> Self {
        Self::SpawnObject {
            obj_type: args.obj_type,
            zone_id: args.zone_id,
            tiles: args.tiles,
}
}
}

impl __sdk::InModule for SpawnObjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_object`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_object {
    /// Request that the remote module invoke the reducer `spawn_object` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_object:spawn_object_then`] to run a callback after the reducer completes.
    fn spawn_object(&self, obj_type: u8,
zone_id: u32,
tiles: Vec::<u8>,
) -> __sdk::Result<()> {
        self.spawn_object_then(obj_type, zone_id, tiles,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_object` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_object_then(
        &self,
        obj_type: u8,
zone_id: u32,
tiles: Vec::<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_object for super::RemoteReducers {
    fn spawn_object_then(
        &self,
        obj_type: u8,
zone_id: u32,
tiles: Vec::<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SpawnObjectArgs { obj_type, zone_id, tiles,  }, callback)
    }
}

