// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MintCounter {
    pub id: u8,
    pub next: u32,
}


impl __sdk::InModule for MintCounter {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `MintCounter`.
///
/// Provides typed access to columns for query building.
pub struct MintCounterCols {
    pub id: __sdk::__query_builder::Col<MintCounter, u8>,
    pub next: __sdk::__query_builder::Col<MintCounter, u32>,
}

impl __sdk::__query_builder::HasCols for MintCounter {
    type Cols = MintCounterCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MintCounterCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            next: __sdk::__query_builder::Col::new(table_name, "next"),

        }
    }
}

/// Indexed column accessor struct for the table `MintCounter`.
///
/// Provides typed access to indexed columns for query building.
pub struct MintCounterIxCols {
    pub id: __sdk::__query_builder::IxCol<MintCounter, u8>,
}

impl __sdk::__query_builder::HasIxCols for MintCounter {
    type IxCols = MintCounterIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MintCounterIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MintCounter {}

