// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetTileArgs {
    pub macro_position: u16,
    pub subtype_id: u16,
    pub layer_id: u8,
    pub tile_reference: u8,
    pub kind_reference: u16,
}

impl From<SetTileArgs> for super::Reducer {
    fn from(args: SetTileArgs) -> Self {
        Self::SetTile {
            macro_position: args.macro_position,
            subtype_id: args.subtype_id,
            layer_id: args.layer_id,
            tile_reference: args.tile_reference,
            kind_reference: args.kind_reference,
}
}
}

impl __sdk::InModule for SetTileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_tile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_tile {
    /// Request that the remote module invoke the reducer `set_tile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_tile:set_tile_then`] to run a callback after the reducer completes.
    fn set_tile(&self, macro_position: u16,
subtype_id: u16,
layer_id: u8,
tile_reference: u8,
kind_reference: u16,
) -> __sdk::Result<()> {
        self.set_tile_then(macro_position, subtype_id, layer_id, tile_reference, kind_reference,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_tile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_tile_then(
        &self,
        macro_position: u16,
subtype_id: u16,
layer_id: u8,
tile_reference: u8,
kind_reference: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_tile for super::RemoteReducers {
    fn set_tile_then(
        &self,
        macro_position: u16,
subtype_id: u16,
layer_id: u8,
tile_reference: u8,
kind_reference: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetTileArgs { macro_position, subtype_id, layer_id, tile_reference, kind_reference,  }, callback)
    }
}

