// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ColdTile {
    pub cold_row_reference: u32,
    pub macro_position_reference: u16,
    pub layer_reference: u8,
    pub tiles: Vec::<u16>,
}


impl __sdk::InModule for ColdTile {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ColdTile`.
///
/// Provides typed access to columns for query building.
pub struct ColdTileCols {
    pub cold_row_reference: __sdk::__query_builder::Col<ColdTile, u32>,
    pub macro_position_reference: __sdk::__query_builder::Col<ColdTile, u16>,
    pub layer_reference: __sdk::__query_builder::Col<ColdTile, u8>,
    pub tiles: __sdk::__query_builder::Col<ColdTile, Vec::<u16>>,
}

impl __sdk::__query_builder::HasCols for ColdTile {
    type Cols = ColdTileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ColdTileCols {
            cold_row_reference: __sdk::__query_builder::Col::new(table_name, "cold_row_reference"),
            macro_position_reference: __sdk::__query_builder::Col::new(table_name, "macro_position_reference"),
            layer_reference: __sdk::__query_builder::Col::new(table_name, "layer_reference"),
            tiles: __sdk::__query_builder::Col::new(table_name, "tiles"),

        }
    }
}

/// Indexed column accessor struct for the table `ColdTile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ColdTileIxCols {
    pub cold_row_reference: __sdk::__query_builder::IxCol<ColdTile, u32>,
    pub macro_position_reference: __sdk::__query_builder::IxCol<ColdTile, u16>,
}

impl __sdk::__query_builder::HasIxCols for ColdTile {
    type IxCols = ColdTileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ColdTileIxCols {
            cold_row_reference: __sdk::__query_builder::IxCol::new(table_name, "cold_row_reference"),
            macro_position_reference: __sdk::__query_builder::IxCol::new(table_name, "macro_position_reference"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ColdTile {}

