// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimOverlayArgs {
    pub rows: Vec::<u32>,
    pub tic: u16,
    pub worker: u8,
}

impl From<ClaimOverlayArgs> for super::Reducer {
    fn from(args: ClaimOverlayArgs) -> Self {
        Self::ClaimOverlay {
            rows: args.rows,
            tic: args.tic,
            worker: args.worker,
}
}
}

impl __sdk::InModule for ClaimOverlayArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_overlay`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_overlay {
    /// Request that the remote module invoke the reducer `claim_overlay` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_overlay:claim_overlay_then`] to run a callback after the reducer completes.
    fn claim_overlay(&self, rows: Vec::<u32>,
tic: u16,
worker: u8,
) -> __sdk::Result<()> {
        self.claim_overlay_then(rows, tic, worker,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_overlay` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_overlay_then(
        &self,
        rows: Vec::<u32>,
tic: u16,
worker: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_overlay for super::RemoteReducers {
    fn claim_overlay_then(
        &self,
        rows: Vec::<u32>,
tic: u16,
worker: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ClaimOverlayArgs { rows, tic, worker,  }, callback)
    }
}

