// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TargetState {
    pub entity_reference: u32,
    pub definition_reference: u32,
    pub position_reference: u32,
    pub data: u8,
    pub promote: bool,
}


impl __sdk::InModule for TargetState {
    type Module = super::RemoteModule;
}

