// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct QueueArgs {
    pub actions: Vec::<u32>,
}

impl From<QueueArgs> for super::Reducer {
    fn from(args: QueueArgs) -> Self {
        Self::Queue {
            actions: args.actions,
}
}
}

impl __sdk::InModule for QueueArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `queue`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait queue {
    /// Request that the remote module invoke the reducer `queue` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`queue:queue_then`] to run a callback after the reducer completes.
    fn queue(&self, actions: Vec::<u32>,
) -> __sdk::Result<()> {
        self.queue_then(actions,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `queue` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn queue_then(
        &self,
        actions: Vec::<u32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl queue for super::RemoteReducers {
    fn queue_then(
        &self,
        actions: Vec::<u32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(QueueArgs { actions,  }, callback)
    }
}

