// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateFreeThingArgs {
    pub now_ms: u64,
    pub zone_id: u32,
    pub location: u8,
    pub rotation: u8,
    pub id: u16,
    pub offset: u8,
}

impl From<CreateFreeThingArgs> for super::Reducer {
    fn from(args: CreateFreeThingArgs) -> Self {
        Self::CreateFreeThing {
            now_ms: args.now_ms,
            zone_id: args.zone_id,
            location: args.location,
            rotation: args.rotation,
            id: args.id,
            offset: args.offset,
}
}
}

impl __sdk::InModule for CreateFreeThingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_free_thing`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_free_thing {
    /// Request that the remote module invoke the reducer `create_free_thing` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_free_thing:create_free_thing_then`] to run a callback after the reducer completes.
    fn create_free_thing(&self, now_ms: u64,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,
) -> __sdk::Result<()> {
        self.create_free_thing_then(now_ms, zone_id, location, rotation, id, offset,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_free_thing` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_free_thing_then(
        &self,
        now_ms: u64,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_free_thing for super::RemoteReducers {
    fn create_free_thing_then(
        &self,
        now_ms: u64,
zone_id: u32,
location: u8,
rotation: u8,
id: u16,
offset: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CreateFreeThingArgs { now_ms, zone_id, location, rotation, id, offset,  }, callback)
    }
}

