// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::pawn_type::Pawn;

/// Table handle for the table `pawns`.
///
/// Obtain a handle from the [`PawnsTableAccess::pawns`] method on [`super::RemoteTables`],
/// like `ctx.db.pawns()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pawns().on_insert(...)`.
pub struct PawnsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Pawn>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pawns`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PawnsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PawnsTableHandle`], which mediates access to the table `pawns`.
    fn pawns(&self) -> PawnsTableHandle<'_>;
}

impl PawnsTableAccess for super::RemoteTables {
    fn pawns(&self) -> PawnsTableHandle<'_> {
        PawnsTableHandle {
            imp: self.imp.get_table::<Pawn>("pawns"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PawnsInsertCallbackId(__sdk::CallbackId);
pub struct PawnsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PawnsTableHandle<'ctx> {
    type Row = Pawn;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Pawn> + '_ { self.imp.iter() }

    type InsertCallbackId = PawnsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PawnsInsertCallbackId {
        PawnsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PawnsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PawnsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PawnsDeleteCallbackId {
        PawnsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PawnsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PawnsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PawnsTableHandle<'ctx> {
    type UpdateCallbackId = PawnsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PawnsUpdateCallbackId {
        PawnsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PawnsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `valid_at` unique index on the table `pawns`,
        /// which allows point queries on the field of the same name
        /// via the [`PawnsValidAtUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.pawns().valid_at().find(...)`.
        pub struct PawnsValidAtUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Pawn, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> PawnsTableHandle<'ctx> {
            /// Get a handle on the `valid_at` unique index on the table `pawns`.
            pub fn valid_at(&self) -> PawnsValidAtUnique<'ctx> {
                PawnsValidAtUnique {
                    imp: self.imp.get_unique_constraint::<u64>("valid_at"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> PawnsValidAtUnique<'ctx> {
            /// Find the subscribed row whose `valid_at` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Pawn> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Pawn>("pawns");
    _table.add_unique_constraint::<u64>("valid_at", |row| &row.valid_at);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Pawn>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Pawn>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Pawn`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait pawnsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Pawn`.
            fn pawns(&self) -> __sdk::__query_builder::Table<Pawn>;
        }

        impl pawnsQueryTableAccess for __sdk::QueryTableAccessor {
            fn pawns(&self) -> __sdk::__query_builder::Table<Pawn> {
                __sdk::__query_builder::Table::new("pawns")
            }
        }

