// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Presence {
    pub region_id: u32,
    pub count: u32,
}


impl __sdk::InModule for Presence {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Presence`.
///
/// Provides typed access to columns for query building.
pub struct PresenceCols {
    pub region_id: __sdk::__query_builder::Col<Presence, u32>,
    pub count: __sdk::__query_builder::Col<Presence, u32>,
}

impl __sdk::__query_builder::HasCols for Presence {
    type Cols = PresenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PresenceCols {
            region_id: __sdk::__query_builder::Col::new(table_name, "region_id"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),

        }
    }
}

/// Indexed column accessor struct for the table `Presence`.
///
/// Provides typed access to indexed columns for query building.
pub struct PresenceIxCols {
    pub region_id: __sdk::__query_builder::IxCol<Presence, u32>,
}

impl __sdk::__query_builder::HasIxCols for Presence {
    type IxCols = PresenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PresenceIxCols {
            region_id: __sdk::__query_builder::IxCol::new(table_name, "region_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Presence {}

