// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetServerArgs {
    pub server_id: u16,
    pub url: String,
    pub now_ms: u64,
}

impl From<SetServerArgs> for super::Reducer {
    fn from(args: SetServerArgs) -> Self {
        Self::SetServer {
            server_id: args.server_id,
            url: args.url,
            now_ms: args.now_ms,
}
}
}

impl __sdk::InModule for SetServerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_server`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_server {
    /// Request that the remote module invoke the reducer `set_server` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_server:set_server_then`] to run a callback after the reducer completes.
    fn set_server(&self, server_id: u16,
url: String,
now_ms: u64,
) -> __sdk::Result<()> {
        self.set_server_then(server_id, url, now_ms,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_server` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_server_then(
        &self,
        server_id: u16,
url: String,
now_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_server for super::RemoteReducers {
    fn set_server_then(
        &self,
        server_id: u16,
url: String,
now_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetServerArgs { server_id, url, now_ms,  }, callback)
    }
}

