// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GrantConditionArgs {
    pub worker: u8,
    pub tic: u16,
    pub entity_reference: u32,
    pub row: u64,
}

impl From<GrantConditionArgs> for super::Reducer {
    fn from(args: GrantConditionArgs) -> Self {
        Self::GrantCondition {
            worker: args.worker,
            tic: args.tic,
            entity_reference: args.entity_reference,
            row: args.row,
}
}
}

impl __sdk::InModule for GrantConditionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `grant_condition`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait grant_condition {
    /// Request that the remote module invoke the reducer `grant_condition` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`grant_condition:grant_condition_then`] to run a callback after the reducer completes.
    fn grant_condition(&self, worker: u8,
tic: u16,
entity_reference: u32,
row: u64,
) -> __sdk::Result<()> {
        self.grant_condition_then(worker, tic, entity_reference, row,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `grant_condition` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn grant_condition_then(
        &self,
        worker: u8,
tic: u16,
entity_reference: u32,
row: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl grant_condition for super::RemoteReducers {
    fn grant_condition_then(
        &self,
        worker: u8,
tic: u16,
entity_reference: u32,
row: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(GrantConditionArgs { worker, tic, entity_reference, row,  }, callback)
    }
}

