// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::payload_log_type::PayloadLog;

/// Table handle for the table `payload_log`.
///
/// Obtain a handle from the [`PayloadLogTableAccess::payload_log`] method on [`super::RemoteTables`],
/// like `ctx.db.payload_log()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.payload_log().on_insert(...)`.
pub struct PayloadLogTableHandle<'ctx> {
    imp: __sdk::TableHandle<PayloadLog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `payload_log`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PayloadLogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PayloadLogTableHandle`], which mediates access to the table `payload_log`.
    fn payload_log(&self) -> PayloadLogTableHandle<'_>;
}

impl PayloadLogTableAccess for super::RemoteTables {
    fn payload_log(&self) -> PayloadLogTableHandle<'_> {
        PayloadLogTableHandle {
            imp: self.imp.get_table::<PayloadLog>("payload_log"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PayloadLogInsertCallbackId(__sdk::CallbackId);
pub struct PayloadLogDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PayloadLogTableHandle<'ctx> {
    type Row = PayloadLog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = PayloadLog> + '_ { self.imp.iter() }

    type InsertCallbackId = PayloadLogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PayloadLogInsertCallbackId {
        PayloadLogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PayloadLogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PayloadLogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PayloadLogDeleteCallbackId {
        PayloadLogDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PayloadLogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PayloadLogUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PayloadLogTableHandle<'ctx> {
    type UpdateCallbackId = PayloadLogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PayloadLogUpdateCallbackId {
        PayloadLogUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PayloadLogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `uid` unique index on the table `payload_log`,
        /// which allows point queries on the field of the same name
        /// via the [`PayloadLogUidUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.payload_log().uid().find(...)`.
        pub struct PayloadLogUidUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<PayloadLog, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> PayloadLogTableHandle<'ctx> {
            /// Get a handle on the `uid` unique index on the table `payload_log`.
            pub fn uid(&self) -> PayloadLogUidUnique<'ctx> {
                PayloadLogUidUnique {
                    imp: self.imp.get_unique_constraint::<u64>("uid"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> PayloadLogUidUnique<'ctx> {
            /// Find the subscribed row whose `uid` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<PayloadLog> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<PayloadLog>("payload_log");
    _table.add_unique_constraint::<u64>("uid", |row| &row.uid);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PayloadLog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<PayloadLog>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `PayloadLog`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait payload_logQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `PayloadLog`.
            fn payload_log(&self) -> __sdk::__query_builder::Table<PayloadLog>;
        }

        impl payload_logQueryTableAccess for __sdk::QueryTableAccessor {
            fn payload_log(&self) -> __sdk::__query_builder::Table<PayloadLog> {
                __sdk::__query_builder::Table::new("payload_log")
            }
        }

