// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::cold_thing_type::ColdThing;

/// Table handle for the table `cold_thing`.
///
/// Obtain a handle from the [`ColdThingTableAccess::cold_thing`] method on [`super::RemoteTables`],
/// like `ctx.db.cold_thing()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cold_thing().on_insert(...)`.
pub struct ColdThingTableHandle<'ctx> {
    imp: __sdk::TableHandle<ColdThing>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cold_thing`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ColdThingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ColdThingTableHandle`], which mediates access to the table `cold_thing`.
    fn cold_thing(&self) -> ColdThingTableHandle<'_>;
}

impl ColdThingTableAccess for super::RemoteTables {
    fn cold_thing(&self) -> ColdThingTableHandle<'_> {
        ColdThingTableHandle {
            imp: self.imp.get_table::<ColdThing>("cold_thing"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ColdThingInsertCallbackId(__sdk::CallbackId);
pub struct ColdThingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ColdThingTableHandle<'ctx> {
    type Row = ColdThing;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ColdThing> + '_ { self.imp.iter() }

    type InsertCallbackId = ColdThingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColdThingInsertCallbackId {
        ColdThingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ColdThingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ColdThingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColdThingDeleteCallbackId {
        ColdThingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ColdThingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ColdThingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ColdThingTableHandle<'ctx> {
    type UpdateCallbackId = ColdThingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ColdThingUpdateCallbackId {
        ColdThingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ColdThingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `cold_row_reference` unique index on the table `cold_thing`,
        /// which allows point queries on the field of the same name
        /// via the [`ColdThingColdRowReferenceUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.cold_thing().cold_row_reference().find(...)`.
        pub struct ColdThingColdRowReferenceUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ColdThing, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ColdThingTableHandle<'ctx> {
            /// Get a handle on the `cold_row_reference` unique index on the table `cold_thing`.
            pub fn cold_row_reference(&self) -> ColdThingColdRowReferenceUnique<'ctx> {
                ColdThingColdRowReferenceUnique {
                    imp: self.imp.get_unique_constraint::<u32>("cold_row_reference"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ColdThingColdRowReferenceUnique<'ctx> {
            /// Find the subscribed row whose `cold_row_reference` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<ColdThing> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ColdThing>("cold_thing");
    _table.add_unique_constraint::<u32>("cold_row_reference", |row| &row.cold_row_reference);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ColdThing>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ColdThing>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ColdThing`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait cold_thingQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ColdThing`.
            fn cold_thing(&self) -> __sdk::__query_builder::Table<ColdThing>;
        }

        impl cold_thingQueryTableAccess for __sdk::QueryTableAccessor {
            fn cold_thing(&self) -> __sdk::__query_builder::Table<ColdThing> {
                __sdk::__query_builder::Table::new("cold_thing")
            }
        }

