// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GcOverlayArgs {
    pub horizon: u16,
}

impl From<GcOverlayArgs> for super::Reducer {
    fn from(args: GcOverlayArgs) -> Self {
        Self::GcOverlay {
            horizon: args.horizon,
}
}
}

impl __sdk::InModule for GcOverlayArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `gc_overlay`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait gc_overlay {
    /// Request that the remote module invoke the reducer `gc_overlay` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`gc_overlay:gc_overlay_then`] to run a callback after the reducer completes.
    fn gc_overlay(&self, horizon: u16,
) -> __sdk::Result<()> {
        self.gc_overlay_then(horizon,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `gc_overlay` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn gc_overlay_then(
        &self,
        horizon: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl gc_overlay for super::RemoteReducers {
    fn gc_overlay_then(
        &self,
        horizon: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(GcOverlayArgs { horizon,  }, callback)
    }
}

