// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::overlay_item_type::OverlayItem;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OverlayTarget {
    pub cold_row_reference: u32,
    pub macro_position_reference: u16,
    pub subtype_id: u16,
    pub layer_id: u8,
    pub items: Vec::<OverlayItem>,
    pub promote: bool,
}


impl __sdk::InModule for OverlayTarget {
    type Module = super::RemoteModule;
}

