// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceThingsArgs {
    pub macro_position: u16,
    pub subtype_id: u16,
    pub layer_id: u8,
    pub tile_references: Vec::<u8>,
    pub kind_reference: u16,
    pub data: u8,
}

impl From<PlaceThingsArgs> for super::Reducer {
    fn from(args: PlaceThingsArgs) -> Self {
        Self::PlaceThings {
            macro_position: args.macro_position,
            subtype_id: args.subtype_id,
            layer_id: args.layer_id,
            tile_references: args.tile_references,
            kind_reference: args.kind_reference,
            data: args.data,
}
}
}

impl __sdk::InModule for PlaceThingsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_things`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_things {
    /// Request that the remote module invoke the reducer `place_things` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_things:place_things_then`] to run a callback after the reducer completes.
    fn place_things(&self, macro_position: u16,
subtype_id: u16,
layer_id: u8,
tile_references: Vec::<u8>,
kind_reference: u16,
data: u8,
) -> __sdk::Result<()> {
        self.place_things_then(macro_position, subtype_id, layer_id, tile_references, kind_reference, data,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_things` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_things_then(
        &self,
        macro_position: u16,
subtype_id: u16,
layer_id: u8,
tile_references: Vec::<u8>,
kind_reference: u16,
data: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_things for super::RemoteReducers {
    fn place_things_then(
        &self,
        macro_position: u16,
subtype_id: u16,
layer_id: u8,
tile_references: Vec::<u8>,
kind_reference: u16,
data: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PlaceThingsArgs { macro_position, subtype_id, layer_id, tile_references, kind_reference, data,  }, callback)
    }
}

