// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendArgs {
    pub actions: Vec::<u64>,
    pub targets: Vec::<u64>,
}

impl From<AppendArgs> for super::Reducer {
    fn from(args: AppendArgs) -> Self {
        Self::Append {
            actions: args.actions,
            targets: args.targets,
}
}
}

impl __sdk::InModule for AppendArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append {
    /// Request that the remote module invoke the reducer `append` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append:append_then`] to run a callback after the reducer completes.
    fn append(&self, actions: Vec::<u64>,
targets: Vec::<u64>,
) -> __sdk::Result<()> {
        self.append_then(actions, targets,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_then(
        &self,
        actions: Vec::<u64>,
targets: Vec::<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append for super::RemoteReducers {
    fn append_then(
        &self,
        actions: Vec::<u64>,
targets: Vec::<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AppendArgs { actions, targets,  }, callback)
    }
}

