// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Cold {
    pub cold_row_reference: u64,
    pub macro_position: u16,
    pub type_reference: u16,
    pub layer_id: u8,
    pub kinds: Vec::<u32>,
    pub version: u32,
}


impl __sdk::InModule for Cold {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Cold`.
///
/// Provides typed access to columns for query building.
pub struct ColdCols {
    pub cold_row_reference: __sdk::__query_builder::Col<Cold, u64>,
    pub macro_position: __sdk::__query_builder::Col<Cold, u16>,
    pub type_reference: __sdk::__query_builder::Col<Cold, u16>,
    pub layer_id: __sdk::__query_builder::Col<Cold, u8>,
    pub kinds: __sdk::__query_builder::Col<Cold, Vec::<u32>>,
    pub version: __sdk::__query_builder::Col<Cold, u32>,
}

impl __sdk::__query_builder::HasCols for Cold {
    type Cols = ColdCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ColdCols {
            cold_row_reference: __sdk::__query_builder::Col::new(table_name, "cold_row_reference"),
            macro_position: __sdk::__query_builder::Col::new(table_name, "macro_position"),
            type_reference: __sdk::__query_builder::Col::new(table_name, "type_reference"),
            layer_id: __sdk::__query_builder::Col::new(table_name, "layer_id"),
            kinds: __sdk::__query_builder::Col::new(table_name, "kinds"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),

        }
    }
}

/// Indexed column accessor struct for the table `Cold`.
///
/// Provides typed access to indexed columns for query building.
pub struct ColdIxCols {
    pub cold_row_reference: __sdk::__query_builder::IxCol<Cold, u64>,
    pub macro_position: __sdk::__query_builder::IxCol<Cold, u16>,
}

impl __sdk::__query_builder::HasIxCols for Cold {
    type IxCols = ColdIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ColdIxCols {
            cold_row_reference: __sdk::__query_builder::IxCol::new(table_name, "cold_row_reference"),
            macro_position: __sdk::__query_builder::IxCol::new(table_name, "macro_position"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Cold {}

