// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::cold_removed_type::ColdRemoved;

/// Table handle for the table `cold_removed`.
///
/// Obtain a handle from the [`ColdRemovedTableAccess::cold_removed`] method on [`super::RemoteTables`],
/// like `ctx.db.cold_removed()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cold_removed().on_insert(...)`.
pub struct ColdRemovedTableHandle<'ctx> {
    imp: __sdk::TableHandle<ColdRemoved>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cold_removed`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ColdRemovedTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ColdRemovedTableHandle`], which mediates access to the table `cold_removed`.
    fn cold_removed(&self) -> ColdRemovedTableHandle<'_>;
}

impl ColdRemovedTableAccess for super::RemoteTables {
    fn cold_removed(&self) -> ColdRemovedTableHandle<'_> {
        ColdRemovedTableHandle {
            imp: self.imp.get_table::<ColdRemoved>("cold_removed"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ColdRemovedInsertCallbackId(__sdk::CallbackId);
pub struct ColdRemovedDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ColdRemovedTableHandle<'ctx> {
    type Row = ColdRemoved;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ColdRemoved> + '_ { self.imp.iter() }

    type InsertCallbackId = ColdRemovedInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColdRemovedInsertCallbackId {
        ColdRemovedInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ColdRemovedInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ColdRemovedDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColdRemovedDeleteCallbackId {
        ColdRemovedDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ColdRemovedDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ColdRemovedUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ColdRemovedTableHandle<'ctx> {
    type UpdateCallbackId = ColdRemovedUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ColdRemovedUpdateCallbackId {
        ColdRemovedUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ColdRemovedUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `zone_key` unique index on the table `cold_removed`,
        /// which allows point queries on the field of the same name
        /// via the [`ColdRemovedZoneKeyUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.cold_removed().zone_key().find(...)`.
        pub struct ColdRemovedZoneKeyUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ColdRemoved, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ColdRemovedTableHandle<'ctx> {
            /// Get a handle on the `zone_key` unique index on the table `cold_removed`.
            pub fn zone_key(&self) -> ColdRemovedZoneKeyUnique<'ctx> {
                ColdRemovedZoneKeyUnique {
                    imp: self.imp.get_unique_constraint::<u32>("zone_key"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ColdRemovedZoneKeyUnique<'ctx> {
            /// Find the subscribed row whose `zone_key` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<ColdRemoved> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ColdRemoved>("cold_removed");
    _table.add_unique_constraint::<u32>("zone_key", |row| &row.zone_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ColdRemoved>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ColdRemoved>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ColdRemoved`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait cold_removedQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ColdRemoved`.
            fn cold_removed(&self) -> __sdk::__query_builder::Table<ColdRemoved>;
        }

        impl cold_removedQueryTableAccess for __sdk::QueryTableAccessor {
            fn cold_removed(&self) -> __sdk::__query_builder::Table<ColdRemoved> {
                __sdk::__query_builder::Table::new("cold_removed")
            }
        }

