// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::event_log_type::EventLog;

/// Table handle for the table `event_log`.
///
/// Obtain a handle from the [`EventLogTableAccess::event_log`] method on [`super::RemoteTables`],
/// like `ctx.db.event_log()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.event_log().on_insert(...)`.
pub struct EventLogTableHandle<'ctx> {
    imp: __sdk::TableHandle<EventLog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `event_log`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EventLogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EventLogTableHandle`], which mediates access to the table `event_log`.
    fn event_log(&self) -> EventLogTableHandle<'_>;
}

impl EventLogTableAccess for super::RemoteTables {
    fn event_log(&self) -> EventLogTableHandle<'_> {
        EventLogTableHandle {
            imp: self.imp.get_table::<EventLog>("event_log"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EventLogInsertCallbackId(__sdk::CallbackId);
pub struct EventLogDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EventLogTableHandle<'ctx> {
    type Row = EventLog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = EventLog> + '_ { self.imp.iter() }

    type InsertCallbackId = EventLogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EventLogInsertCallbackId {
        EventLogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EventLogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EventLogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EventLogDeleteCallbackId {
        EventLogDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EventLogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EventLogUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EventLogTableHandle<'ctx> {
    type UpdateCallbackId = EventLogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EventLogUpdateCallbackId {
        EventLogUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EventLogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `event_reference` unique index on the table `event_log`,
        /// which allows point queries on the field of the same name
        /// via the [`EventLogEventReferenceUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.event_log().event_reference().find(...)`.
        pub struct EventLogEventReferenceUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<EventLog, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> EventLogTableHandle<'ctx> {
            /// Get a handle on the `event_reference` unique index on the table `event_log`.
            pub fn event_reference(&self) -> EventLogEventReferenceUnique<'ctx> {
                EventLogEventReferenceUnique {
                    imp: self.imp.get_unique_constraint::<u32>("event_reference"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> EventLogEventReferenceUnique<'ctx> {
            /// Find the subscribed row whose `event_reference` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<EventLog> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<EventLog>("event_log");
    _table.add_unique_constraint::<u32>("event_reference", |row| &row.event_reference);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EventLog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<EventLog>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `EventLog`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait event_logQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `EventLog`.
            fn event_log(&self) -> __sdk::__query_builder::Table<EventLog>;
        }

        impl event_logQueryTableAccess for __sdk::QueryTableAccessor {
            fn event_log(&self) -> __sdk::__query_builder::Table<EventLog> {
                __sdk::__query_builder::Table::new("event_log")
            }
        }

