// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::open_rows_type::OpenRows;

/// Table handle for the table `open_rows`.
///
/// Obtain a handle from the [`OpenRowsTableAccess::open_rows`] method on [`super::RemoteTables`],
/// like `ctx.db.open_rows()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.open_rows().on_insert(...)`.
pub struct OpenRowsTableHandle<'ctx> {
    imp: __sdk::TableHandle<OpenRows>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `open_rows`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OpenRowsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OpenRowsTableHandle`], which mediates access to the table `open_rows`.
    fn open_rows(&self) -> OpenRowsTableHandle<'_>;
}

impl OpenRowsTableAccess for super::RemoteTables {
    fn open_rows(&self) -> OpenRowsTableHandle<'_> {
        OpenRowsTableHandle {
            imp: self.imp.get_table::<OpenRows>("open_rows"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OpenRowsInsertCallbackId(__sdk::CallbackId);
pub struct OpenRowsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for OpenRowsTableHandle<'ctx> {
    type Row = OpenRows;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = OpenRows> + '_ { self.imp.iter() }

    type InsertCallbackId = OpenRowsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OpenRowsInsertCallbackId {
        OpenRowsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OpenRowsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OpenRowsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OpenRowsDeleteCallbackId {
        OpenRowsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OpenRowsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct OpenRowsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for OpenRowsTableHandle<'ctx> {
    type UpdateCallbackId = OpenRowsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OpenRowsUpdateCallbackId {
        OpenRowsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OpenRowsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `id` unique index on the table `open_rows`,
        /// which allows point queries on the field of the same name
        /// via the [`OpenRowsIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.open_rows().id().find(...)`.
        pub struct OpenRowsIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<OpenRows, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> OpenRowsTableHandle<'ctx> {
            /// Get a handle on the `id` unique index on the table `open_rows`.
            pub fn id(&self) -> OpenRowsIdUnique<'ctx> {
                OpenRowsIdUnique {
                    imp: self.imp.get_unique_constraint::<u64>("id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> OpenRowsIdUnique<'ctx> {
            /// Find the subscribed row whose `id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<OpenRows> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<OpenRows>("open_rows");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OpenRows>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<OpenRows>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `OpenRows`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait open_rowsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `OpenRows`.
            fn open_rows(&self) -> __sdk::__query_builder::Table<OpenRows>;
        }

        impl open_rowsQueryTableAccess for __sdk::QueryTableAccessor {
            fn open_rows(&self) -> __sdk::__query_builder::Table<OpenRows> {
                __sdk::__query_builder::Table::new("open_rows")
            }
        }

