// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OpenRows {
    pub id: u64,
    pub event_reference: u32,
    pub source_shard: u16,
    pub state_log_id: u64,
}


impl __sdk::InModule for OpenRows {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `OpenRows`.
///
/// Provides typed access to columns for query building.
pub struct OpenRowsCols {
    pub id: __sdk::__query_builder::Col<OpenRows, u64>,
    pub event_reference: __sdk::__query_builder::Col<OpenRows, u32>,
    pub source_shard: __sdk::__query_builder::Col<OpenRows, u16>,
    pub state_log_id: __sdk::__query_builder::Col<OpenRows, u64>,
}

impl __sdk::__query_builder::HasCols for OpenRows {
    type Cols = OpenRowsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OpenRowsCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            event_reference: __sdk::__query_builder::Col::new(table_name, "event_reference"),
            source_shard: __sdk::__query_builder::Col::new(table_name, "source_shard"),
            state_log_id: __sdk::__query_builder::Col::new(table_name, "state_log_id"),

        }
    }
}

/// Indexed column accessor struct for the table `OpenRows`.
///
/// Provides typed access to indexed columns for query building.
pub struct OpenRowsIxCols {
    pub event_reference: __sdk::__query_builder::IxCol<OpenRows, u32>,
    pub id: __sdk::__query_builder::IxCol<OpenRows, u64>,
}

impl __sdk::__query_builder::HasIxCols for OpenRows {
    type IxCols = OpenRowsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OpenRowsIxCols {
            event_reference: __sdk::__query_builder::IxCol::new(table_name, "event_reference"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OpenRows {}

