// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PackArgs {
    pub entity_key: u64,
    pub zone_id: u32,
    pub type_reference: u32,
    pub object_kind_reference: u32,
}

impl From<PackArgs> for super::Reducer {
    fn from(args: PackArgs) -> Self {
        Self::Pack {
            entity_key: args.entity_key,
            zone_id: args.zone_id,
            type_reference: args.type_reference,
            object_kind_reference: args.object_kind_reference,
}
}
}

impl __sdk::InModule for PackArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pack`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pack {
    /// Request that the remote module invoke the reducer `pack` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pack:pack_then`] to run a callback after the reducer completes.
    fn pack(&self, entity_key: u64,
zone_id: u32,
type_reference: u32,
object_kind_reference: u32,
) -> __sdk::Result<()> {
        self.pack_then(entity_key, zone_id, type_reference, object_kind_reference,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `pack` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pack_then(
        &self,
        entity_key: u64,
zone_id: u32,
type_reference: u32,
object_kind_reference: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl pack for super::RemoteReducers {
    fn pack_then(
        &self,
        entity_key: u64,
zone_id: u32,
type_reference: u32,
object_kind_reference: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PackArgs { entity_key, zone_id, type_reference, object_kind_reference,  }, callback)
    }
}

