// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedColdRowArgs {
    pub macro_position: u16,
    pub type_reference: u16,
    pub layer_id: u8,
    pub kinds: Vec::<u32>,
}

impl From<SeedColdRowArgs> for super::Reducer {
    fn from(args: SeedColdRowArgs) -> Self {
        Self::SeedColdRow {
            macro_position: args.macro_position,
            type_reference: args.type_reference,
            layer_id: args.layer_id,
            kinds: args.kinds,
}
}
}

impl __sdk::InModule for SeedColdRowArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_cold_row`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_cold_row {
    /// Request that the remote module invoke the reducer `seed_cold_row` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_cold_row:seed_cold_row_then`] to run a callback after the reducer completes.
    fn seed_cold_row(&self, macro_position: u16,
type_reference: u16,
layer_id: u8,
kinds: Vec::<u32>,
) -> __sdk::Result<()> {
        self.seed_cold_row_then(macro_position, type_reference, layer_id, kinds,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_cold_row` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_cold_row_then(
        &self,
        macro_position: u16,
type_reference: u16,
layer_id: u8,
kinds: Vec::<u32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_cold_row for super::RemoteReducers {
    fn seed_cold_row_then(
        &self,
        macro_position: u16,
type_reference: u16,
layer_id: u8,
kinds: Vec::<u32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SeedColdRowArgs { macro_position, type_reference, layer_id, kinds,  }, callback)
    }
}

