// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub valid_at: u64,
    pub data_shard: u16,
    pub player_id: u32,
    pub name: String,
    pub last_login_secs: u32,
    pub flags: u32,
}


impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub valid_at: __sdk::__query_builder::Col<Player, u64>,
    pub data_shard: __sdk::__query_builder::Col<Player, u16>,
    pub player_id: __sdk::__query_builder::Col<Player, u32>,
    pub name: __sdk::__query_builder::Col<Player, String>,
    pub last_login_secs: __sdk::__query_builder::Col<Player, u32>,
    pub flags: __sdk::__query_builder::Col<Player, u32>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            valid_at: __sdk::__query_builder::Col::new(table_name, "valid_at"),
            data_shard: __sdk::__query_builder::Col::new(table_name, "data_shard"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            last_login_secs: __sdk::__query_builder::Col::new(table_name, "last_login_secs"),
            flags: __sdk::__query_builder::Col::new(table_name, "flags"),

        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub name: __sdk::__query_builder::IxCol<Player, String>,
    pub player_id: __sdk::__query_builder::IxCol<Player, u32>,
    pub valid_at: __sdk::__query_builder::IxCol<Player, u64>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
            valid_at: __sdk::__query_builder::IxCol::new(table_name, "valid_at"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}

