// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetPlayerPermissionsArgs {
    pub player_id: u32,
    pub time_ms: u64,
    pub perms: u8,
}

impl From<SetPlayerPermissionsArgs> for super::Reducer {
    fn from(args: SetPlayerPermissionsArgs) -> Self {
        Self::SetPlayerPermissions {
            player_id: args.player_id,
            time_ms: args.time_ms,
            perms: args.perms,
}
}
}

impl __sdk::InModule for SetPlayerPermissionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_player_permissions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_player_permissions {
    /// Request that the remote module invoke the reducer `set_player_permissions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_player_permissions:set_player_permissions_then`] to run a callback after the reducer completes.
    fn set_player_permissions(&self, player_id: u32,
time_ms: u64,
perms: u8,
) -> __sdk::Result<()> {
        self.set_player_permissions_then(player_id, time_ms, perms,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_player_permissions` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_player_permissions_then(
        &self,
        player_id: u32,
time_ms: u64,
perms: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_player_permissions for super::RemoteReducers {
    fn set_player_permissions_then(
        &self,
        player_id: u32,
time_ms: u64,
perms: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetPlayerPermissionsArgs { player_id, time_ms, perms,  }, callback)
    }
}

