// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::can_exist_type::CanExist;

/// Table handle for the table `can_exist`.
///
/// Obtain a handle from the [`CanExistTableAccess::can_exist`] method on [`super::RemoteTables`],
/// like `ctx.db.can_exist()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.can_exist().on_insert(...)`.
pub struct CanExistTableHandle<'ctx> {
    imp: __sdk::TableHandle<CanExist>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `can_exist`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CanExistTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CanExistTableHandle`], which mediates access to the table `can_exist`.
    fn can_exist(&self) -> CanExistTableHandle<'_>;
}

impl CanExistTableAccess for super::RemoteTables {
    fn can_exist(&self) -> CanExistTableHandle<'_> {
        CanExistTableHandle {
            imp: self.imp.get_table::<CanExist>("can_exist"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CanExistInsertCallbackId(__sdk::CallbackId);
pub struct CanExistDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CanExistTableHandle<'ctx> {
    type Row = CanExist;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = CanExist> + '_ { self.imp.iter() }

    type InsertCallbackId = CanExistInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CanExistInsertCallbackId {
        CanExistInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CanExistInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CanExistDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CanExistDeleteCallbackId {
        CanExistDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CanExistDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CanExistUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CanExistTableHandle<'ctx> {
    type UpdateCallbackId = CanExistUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CanExistUpdateCallbackId {
        CanExistUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CanExistUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `zone_id` unique index on the table `can_exist`,
        /// which allows point queries on the field of the same name
        /// via the [`CanExistZoneIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.can_exist().zone_id().find(...)`.
        pub struct CanExistZoneIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<CanExist, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> CanExistTableHandle<'ctx> {
            /// Get a handle on the `zone_id` unique index on the table `can_exist`.
            pub fn zone_id(&self) -> CanExistZoneIdUnique<'ctx> {
                CanExistZoneIdUnique {
                    imp: self.imp.get_unique_constraint::<u32>("zone_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> CanExistZoneIdUnique<'ctx> {
            /// Find the subscribed row whose `zone_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<CanExist> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<CanExist>("can_exist");
    _table.add_unique_constraint::<u32>("zone_id", |row| &row.zone_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CanExist>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<CanExist>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `CanExist`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait can_existQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `CanExist`.
            fn can_exist(&self) -> __sdk::__query_builder::Table<CanExist>;
        }

        impl can_existQueryTableAccess for __sdk::QueryTableAccessor {
            fn can_exist(&self) -> __sdk::__query_builder::Table<CanExist> {
                __sdk::__query_builder::Table::new("can_exist")
            }
        }

