// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::cold_zone_type::ColdZone;

/// Table handle for the table `cold_zones`.
///
/// Obtain a handle from the [`ColdZonesTableAccess::cold_zones`] method on [`super::RemoteTables`],
/// like `ctx.db.cold_zones()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cold_zones().on_insert(...)`.
pub struct ColdZonesTableHandle<'ctx> {
    imp: __sdk::TableHandle<ColdZone>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cold_zones`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ColdZonesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ColdZonesTableHandle`], which mediates access to the table `cold_zones`.
    fn cold_zones(&self) -> ColdZonesTableHandle<'_>;
}

impl ColdZonesTableAccess for super::RemoteTables {
    fn cold_zones(&self) -> ColdZonesTableHandle<'_> {
        ColdZonesTableHandle {
            imp: self.imp.get_table::<ColdZone>("cold_zones"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ColdZonesInsertCallbackId(__sdk::CallbackId);
pub struct ColdZonesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ColdZonesTableHandle<'ctx> {
    type Row = ColdZone;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = ColdZone> + '_ { self.imp.iter() }

    type InsertCallbackId = ColdZonesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColdZonesInsertCallbackId {
        ColdZonesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ColdZonesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ColdZonesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ColdZonesDeleteCallbackId {
        ColdZonesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ColdZonesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ColdZonesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ColdZonesTableHandle<'ctx> {
    type UpdateCallbackId = ColdZonesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ColdZonesUpdateCallbackId {
        ColdZonesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ColdZonesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `valid_at` unique index on the table `cold_zones`,
        /// which allows point queries on the field of the same name
        /// via the [`ColdZonesValidAtUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.cold_zones().valid_at().find(...)`.
        pub struct ColdZonesValidAtUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<ColdZone, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ColdZonesTableHandle<'ctx> {
            /// Get a handle on the `valid_at` unique index on the table `cold_zones`.
            pub fn valid_at(&self) -> ColdZonesValidAtUnique<'ctx> {
                ColdZonesValidAtUnique {
                    imp: self.imp.get_unique_constraint::<u64>("valid_at"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ColdZonesValidAtUnique<'ctx> {
            /// Find the subscribed row whose `valid_at` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<ColdZone> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<ColdZone>("cold_zones");
    _table.add_unique_constraint::<u64>("valid_at", |row| &row.valid_at);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ColdZone>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<ColdZone>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `ColdZone`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait cold_zonesQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `ColdZone`.
            fn cold_zones(&self) -> __sdk::__query_builder::Table<ColdZone>;
        }

        impl cold_zonesQueryTableAccess for __sdk::QueryTableAccessor {
            fn cold_zones(&self) -> __sdk::__query_builder::Table<ColdZone> {
                __sdk::__query_builder::Table::new("cold_zones")
            }
        }

