// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ColdZone {
    pub valid_at: u64,
    pub zone_id: u32,
    pub tiles: Vec::<u16>,
    pub things: Vec::<u32>,
}


impl __sdk::InModule for ColdZone {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ColdZone`.
///
/// Provides typed access to columns for query building.
pub struct ColdZoneCols {
    pub valid_at: __sdk::__query_builder::Col<ColdZone, u64>,
    pub zone_id: __sdk::__query_builder::Col<ColdZone, u32>,
    pub tiles: __sdk::__query_builder::Col<ColdZone, Vec::<u16>>,
    pub things: __sdk::__query_builder::Col<ColdZone, Vec::<u32>>,
}

impl __sdk::__query_builder::HasCols for ColdZone {
    type Cols = ColdZoneCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ColdZoneCols {
            valid_at: __sdk::__query_builder::Col::new(table_name, "valid_at"),
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            tiles: __sdk::__query_builder::Col::new(table_name, "tiles"),
            things: __sdk::__query_builder::Col::new(table_name, "things"),

        }
    }
}

/// Indexed column accessor struct for the table `ColdZone`.
///
/// Provides typed access to indexed columns for query building.
pub struct ColdZoneIxCols {
    pub valid_at: __sdk::__query_builder::IxCol<ColdZone, u64>,
    pub zone_id: __sdk::__query_builder::IxCol<ColdZone, u32>,
}

impl __sdk::__query_builder::HasIxCols for ColdZone {
    type IxCols = ColdZoneIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ColdZoneIxCols {
            valid_at: __sdk::__query_builder::IxCol::new(table_name, "valid_at"),
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ColdZone {}

