// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::hot_thing_type::HotThing;

/// Table handle for the table `hot_things`.
///
/// Obtain a handle from the [`HotThingsTableAccess::hot_things`] method on [`super::RemoteTables`],
/// like `ctx.db.hot_things()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hot_things().on_insert(...)`.
pub struct HotThingsTableHandle<'ctx> {
    imp: __sdk::TableHandle<HotThing>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hot_things`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HotThingsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HotThingsTableHandle`], which mediates access to the table `hot_things`.
    fn hot_things(&self) -> HotThingsTableHandle<'_>;
}

impl HotThingsTableAccess for super::RemoteTables {
    fn hot_things(&self) -> HotThingsTableHandle<'_> {
        HotThingsTableHandle {
            imp: self.imp.get_table::<HotThing>("hot_things"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HotThingsInsertCallbackId(__sdk::CallbackId);
pub struct HotThingsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for HotThingsTableHandle<'ctx> {
    type Row = HotThing;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = HotThing> + '_ { self.imp.iter() }

    type InsertCallbackId = HotThingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HotThingsInsertCallbackId {
        HotThingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HotThingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HotThingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HotThingsDeleteCallbackId {
        HotThingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HotThingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HotThingsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HotThingsTableHandle<'ctx> {
    type UpdateCallbackId = HotThingsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HotThingsUpdateCallbackId {
        HotThingsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HotThingsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `valid_at` unique index on the table `hot_things`,
        /// which allows point queries on the field of the same name
        /// via the [`HotThingsValidAtUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.hot_things().valid_at().find(...)`.
        pub struct HotThingsValidAtUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<HotThing, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> HotThingsTableHandle<'ctx> {
            /// Get a handle on the `valid_at` unique index on the table `hot_things`.
            pub fn valid_at(&self) -> HotThingsValidAtUnique<'ctx> {
                HotThingsValidAtUnique {
                    imp: self.imp.get_unique_constraint::<u64>("valid_at"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> HotThingsValidAtUnique<'ctx> {
            /// Find the subscribed row whose `valid_at` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<HotThing> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<HotThing>("hot_things");
    _table.add_unique_constraint::<u64>("valid_at", |row| &row.valid_at);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HotThing>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<HotThing>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `HotThing`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait hot_thingsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `HotThing`.
            fn hot_things(&self) -> __sdk::__query_builder::Table<HotThing>;
        }

        impl hot_thingsQueryTableAccess for __sdk::QueryTableAccessor {
            fn hot_things(&self) -> __sdk::__query_builder::Table<HotThing> {
                __sdk::__query_builder::Table::new("hot_things")
            }
        }

