// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedColdZoneArgs {
    pub now_ms: u64,
    pub zone_id: u32,
    pub tiles: Vec::<u16>,
    pub things: Vec::<u32>,
}

impl From<SeedColdZoneArgs> for super::Reducer {
    fn from(args: SeedColdZoneArgs) -> Self {
        Self::SeedColdZone {
            now_ms: args.now_ms,
            zone_id: args.zone_id,
            tiles: args.tiles,
            things: args.things,
}
}
}

impl __sdk::InModule for SeedColdZoneArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_cold_zone`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_cold_zone {
    /// Request that the remote module invoke the reducer `seed_cold_zone` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_cold_zone:seed_cold_zone_then`] to run a callback after the reducer completes.
    fn seed_cold_zone(&self, now_ms: u64,
zone_id: u32,
tiles: Vec::<u16>,
things: Vec::<u32>,
) -> __sdk::Result<()> {
        self.seed_cold_zone_then(now_ms, zone_id, tiles, things,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_cold_zone` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_cold_zone_then(
        &self,
        now_ms: u64,
zone_id: u32,
tiles: Vec::<u16>,
things: Vec::<u32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_cold_zone for super::RemoteReducers {
    fn seed_cold_zone_then(
        &self,
        now_ms: u64,
zone_id: u32,
tiles: Vec::<u16>,
things: Vec::<u32>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SeedColdZoneArgs { now_ms, zone_id, tiles, things,  }, callback)
    }
}

